nexodus-io/nexodus

internal/apex/apex.go
internal/apex/configure-hub.go
internal/apex/configure-pull.go
internal/apex/configure-utils.go
internal/apex/utils.go
internal/handlers/peer.go
internal/models/peer.go

Convert AllowedIPs to be a slice

---

.gitleaks.toml

Allow secrets used for integration testing and local deployments

---

ui/src/pages/Dashboard.tsx

ui: s/Aped/Apex/

---

Containerfile.ui
deploy/apex-ingress-openshift.yaml
deploy/apex-ingress.yaml
deploy/apex-openshift.yaml

Manifest files for deploying apex on openshift

---

ui/src/pages/Dashboard.tsx

ui: Fix a couple more wording issues on the dashboard

---

integration-tests/integration_test.go
integration-tests/util_test.go
internal/client/user.go
internal/client/zone.go

Adds additional go IT and utils

---

docs/design/design-discovery.md

Added discovery design doc

---

ui/src/App.tsx
ui/src/pages/Devices.tsx
ui/src/pages/Peers.tsx
ui/src/pages/Users.tsx

This PR updates the UI to use friendly names for resources in more places.

ui: Use friendly names in more places

---

tests/e2e-scripts/init-containers.sh

fixes IT zone create api call

---

ops/ansible/README.md
ops/ansible/aws/create-zone/tasks/main.yml
ops/ansible/aws/deploy-hub-router/tasks/main.yml
ops/ansible/aws/deploy-mesh/tasks/main.yml
ops/ansible/aws/start-apex-agent/tasks/main.yml
ops/ansible/aws/vars.yml
ops/ansible/azure/deploy-mesh/tasks/main.yml
ops/ansible/azure/start-apex-agent/tasks/main.yml
ops/ansible/azure/vars.yml
ops/ansible/gcp/deploy-mesh/tasks/main.yml
ops/ansible/gcp/start-apex-agent/tasks/main.yml
ops/ansible/gcp/vars.yml

Update playbooks with dex auth

---

README.md
docs/security.md

This change introduces a set of guiding principles for the project. These principles should be things that the whole team agrees on and feels passionately about. These principles should be used to guide decision making as the project continues to evolve.
There are a few other minor cleanups to other text included, as well.

README.md: Add Guiding Principles

---

.github/workflows/images.yml

ci: Fix image names

---

ops/ansible/aws/create-zone/tasks/main.yml
ops/ansible/aws/deploy-mesh/tasks/main.yml
ops/ansible/aws/rootCA.pem
ops/ansible/azure/deploy-mesh/tasks/main.yml
ops/ansible/azure/rootCA.pem
ops/ansible/gcp/deploy-mesh/tasks/main.yml
ops/ansible/gcp/rootCA.pem

Update playbooks with https rootCA cert handling

---

docs/README.md

docs: Fix typo in HTTPS instructions

---

internal/apex/apex.go
internal/apex/utils.go
internal/apex/wg-deploy.go

Fix Darwin userspace interface checks

---

Containerfile.test
Makefile
cmd/apexctl/device.go
cmd/apexctl/main.go
cmd/apexctl/peer.go
cmd/apexctl/zone.go
integration-tests/integration_test.go
integration-tests/util_test.go
internal/client/device.go
internal/client/peers.go
internal/client/user.go
internal/client/zone.go
internal/handlers/device.go
internal/handlers/peer.go
internal/handlers/zone.go
internal/ipam/ipam.go
internal/routers/routers.go

- Added various ctl commands for all tables.
- Device, Zone, Peer deletes (including IPAM releasing back to a pool) as part of #153

Added apexctl commands

---

cmd/apexctl/main.go
cmd/apexctl/user.go
integration-tests/integration_test.go
internal/client/user.go
internal/client/zone.go
internal/handlers/device.go
internal/handlers/peer.go
internal/handlers/user.go
internal/ipam/ipam.go
internal/routers/routers.go

User endpoint deletes and child-prefix ipam releases

---

.github/workflows/deploy.yml

ci: Add deploy workflow

---

deploy/apex/overlays/operate-first/files/config.yaml

operate-first: Use in-memory dex storage for now

---

deploy/apex/overlays/operate-first/kustomization.yaml

Small Operate First Fix

---

docs/deployment.md

docs: Add Deployment Docs

---

.github/workflows/deploy.yml
deploy/apex/base/apiproxy/deployment.yaml
deploy/apex/base/backend-cli/deployment.yaml
deploy/apex/base/backend-web/deployment.yaml
deploy/apex/base/dex/deployment.yaml
deploy/apex/base/frontend/deployment.yaml

- Fixes commit message in deploy pipeline
- Removes unnecessary labels/selectors from kube yaml as kustomize injects these for us...
E.g Snippet from `kustomize build` once these labels were removed from the frontend deployment file...
```
apiVersion: apps/v1
kind: Deployment
metadata:
labels:
app.kubernetes.io/component: frontend
app.kubernetes.io/instance: frontend
app.kubernetes.io/name: frontend
app.kubernetes.io/part-of: apex
name: frontend
namespace: apex
spec:
replicas: 1
selector:
matchLabels:
app.kubernetes.io/component: frontend
app.kubernetes.io/instance: frontend
app.kubernetes.io/name: frontend
app.kubernetes.io/part-of: apex
```

Fix deploy again

---

.vscode/settings.json

vscode: Set schema for deploy.yaml

---

deploy/apex/base/apiproxy/ingress.yaml
deploy/apex/base/dex/ingress.yaml
deploy/apex/base/frontend/ingress.yaml

deploy: Remove Nginx IngressClass

---

deploy/apex/overlays/operate-first/kustomization.yaml

operate-first: Fix Redirect URL

---

.github/workflows/build.yml
.github/workflows/deploy.yml
deploy/apex/base/apiserver/deployment.yaml
deploy/apex/base/apiserver/postgres.yaml
deploy/apex/base/ipam/deployment.yaml
deploy/apex/base/ipam/postgres.yaml
deploy/kind.yaml
hack/kind/kind.sh
internal/database/logger.go
internal/routers/routers.go

We can't schedule our postgres instances as we've exceeded our resource quota :(

deploy: Cap postgres resources

---

deploy/apex/base/apiserver/postgres.yaml
deploy/apex/base/ipam/postgres.yaml

deploy: quarter postgres cpu req/limit

---

docs/README.md

https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/

docs: Replace ascii diagram with mermaid

---

ui/src/pages/Dashboard.tsx

ui: Provide quickstart instructions in the dashboard

---

.github/workflows/deploy.yml

Publish multi-arch images for apiserver/frontend

---

.github/workflows/deploy.yml

Fix docker build. Add missing buildx/qemu action steps

---

internal/apex/apex.go
internal/apex/route.go
internal/apex/utils.go
internal/apex/wg-deploy.go
internal/apex/wg-iface.go
internal/apex/wg-peers.go
internal/apex/wg.go

Set tunnel interface in the apex struct

---

hack/kind/kind.sh

Add check for dependencies to ensure required dependencies are installed.

---

hack/kind/kind.sh

Remove debug flag from kind.sh

---

deploy/apex/overlays/qa/issuer.yaml

deploy: qa use different email address

---

hack/kind/kind.sh

Signed-off-by: Hiram Chirino <hiram@hiramchirino.com>

fix: allow kind.sh script work with osx's slightly different sed command

---

ui/src/pages/Devices.tsx
ui/src/pages/Peers.tsx
ui/src/pages/Users.tsx
ui/src/pages/Zones.tsx

This PR adds delete support for Users, Devices, Zones, and Peers. It depends on PR #265 because the Zone delete button is disabled if the feature is turned off by its feature flag.
Closes #155

ui: Implement deletes

---

hack/kind/kind.sh

by installing all the operators in parallel and then wait their Readiness before installing Apex.

chore: speed up kind.sh up a little 

---

ops/ansible/aws/create-zone/tasks/main.yml
ops/ansible/aws/deploy-hub-router/tasks/main.yml
ops/ansible/aws/deploy-mesh/tasks/main.yml
ops/ansible/aws/start-apex-agent/tasks/main.yml
ops/ansible/aws/vars.yml
ops/ansible/azure/deploy-mesh/tasks/main.yml
ops/ansible/azure/start-apex-agent/tasks/main.yml
ops/ansible/azure/vars.yml
ops/ansible/gcp/deploy-mesh/tasks/main.yml
ops/ansible/gcp/start-apex-agent/tasks/main.yml
ops/ansible/gcp/vars.yml

Update playbooks for keycloak

---

docs/README.md

Update install docs

---

ops/ansible/aws/create-zone/tasks/main.yml
ops/ansible/aws/deploy-hub-router/tasks/main.yml
ops/ansible/aws/deploy-mesh/tasks/main.yml
ops/ansible/azure/deploy-mesh/tasks/main.yml
ops/ansible/gcp/deploy-mesh/tasks/main.yml

Rename apex -> apexd in playbooks

---

.dockerignore
.gitignore
ops/ansible/README.md

Remove docker compose remanent

---

Makefile
docs/README.md

Redploy DB via makefile and makefile docs updates

---

hack/api-token.sh
internal/client/auth.go

auth: Fix missing expiry in tokens from DeviceAuth

---

.github/workflows/build.yml
docs/README.md

update docs with installation instructions.

Publish apexctl binary to AWS s3 bucket and

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/enhancement_proposal.yml

Add Bug and Enhancement templates

---

Makefile

Reorganize targets a bit, by splitting out the common kind workflow targets in their own section, grouping the targets that work against an existing kube cluster, and putting the "run-test-container" target under "Development".
```
$ make
Usage:
make <target>
Binaries
apexd               Build the apexd binary for all architectures
clean               clean built binaries
Development
go-lint             Lint the go code
gen-docs            Generate API docs
e2e                 Run e2e tests
test                Run unit tests
run-test-container  Run docker container that you can run apex in
Container Images
test-images         Create test images for e2e
images              Create container images
Kubernetes - kind dev environment
run-on-kind         Setup a kind cluster and deploy apex on …
```

Makefile: Reorganize targets

---

deploy/apex-client/overlays/dev/node_selector.yaml

Github reports yaml lint warning in the PRs for unchanged files as well. That's bit annoying and confusing. 
https://github.com/redhat-et/apex/pull/373/files

Fix formatting in the yaml file

---

internal/client/auth.go

Add offline_access to the one-time auth scope

---

internal/apex/apex.go
internal/apex/wg-deploy.go
internal/apex/wg-iface.go

Fatal out if interface creation operations fail

---

internal/apex/wg-peers.go

I started looking at this when trying the gocyclo linter and it pointed out this method as one of the most complex. I was able to simplify it a bit by:
- only checking if the peer in the large for loop is ourself in one place instead of duplicating it throughout the rest of the loop.
- combining some conditional checks instead of having multiple levels of nested if statements.
I'm not introducing the gocyclo linter in the tree yet, as the required refactorings would disrupt some other work people have in flight.

apexd: Refactor buildPeerConfig()

---

.github/workflows/docs.yml

Fix paths for the docs workflow job

---

Makefile

Add nicer output when doing builds. This patch also reduces some duplication between the targets for different platforms and architectures.
The updated targets will use APEX_LDFLAGS if that's set. This PR doesn't use it, but i have other changes that use it.
You can still see the full commands by setting NOISY_BUILD like this:
```
$ NOISY_BUILD=y make all
```
The default pretty output looks like this:
```
$ make all
[GO LINT]    ./...
[YAML LINT]  ./...
[MD LINT]    ./...
[GO BUILD]   dist/apexd
[GO BUILD]   dist/apexd-linux-arm
[GO BUILD]   dist/apexd-linux-amd64
[GO BUILD]   dist/apexd-darwin-amd64
[GO BUILD]   dist/apexd-darwin-arm64
[GO BUILD]   dist/apexd-windows-amd64
```
This is split out from #341, since it's not directly related to the main changes there.

Makefile: Add pretty output

---

docs/design/database.md

docs: Add database design

---

Makefile

lint: Ignore ui/node_modules for markdown-lint

---

Containerfile.ipam
go.mod
go.sum
internal/handlers/device.go
internal/handlers/organization.go
internal/handlers/user.go
internal/ipam/ipam.go
internal/ipam/ipam_test.go
internal/util/utils.go

feat: namespaced ipam

---

.github/workflows/build.yml
.github/workflows/deploy.yml
.github/workflows/promote.yml
Containerfile.ipam
Makefile
deploy/apex/base/ipam/deployment.yaml
deploy/apex/overlays/prod/kustomization.yaml
deploy/apex/overlays/qa/kustomization.yaml
go.mod
go.sum

This updates our development deployment to use the new IPAM. It also updates github workflows to build and push the IPAM image.

Use New IPAM

---

Makefile
deploy/apex/overlays/arm64/kustomization.yaml
deploy/apex/overlays/arm64/service.yaml
deploy/apex/overlays/arm64/stateful-set.yaml

The crunchydb operator does not work well on arm64, so this implements a simpler deployment of the postgres server.

fix: better support arm64 developer machines

---

integration-tests/integration_test.go

- Resolves some tests by adding discovery nodes to the tests.
- Disables tests involving node delete or request ip operations until they are resolved being tracked in #437.

Fix e2e post schema changes

---

cmd/apexctl/device.go
cmd/apexctl/main.go
cmd/apexd/main.go
integration-tests/integration_test.go
internal/apex/apex.go
internal/apex/route.go
internal/handlers/device.go
internal/handlers/organization.go
internal/ipam/ipam.go
internal/models/device.go

Fix child prefix handling on update

---

Makefile

Also run this target on "make all"

Makefile: Add ui-lint target

---

internal/handlers/device.go

Before this change the following SQL statements were executed when creating a device:
SELECT * FROM "devices" WHERE "devices"."user_id" = '01578c9e-8e76-46a4-b2b2-50788cec2ccd
SELECT * FROM "user_organization" WHERE "user_organization"."user_id" = '01578c9e-8e76-46a4-b2b2-50788cec2ccd'
SELECT * FROM "organizations" WHERE "organizations"."id" = 'd0a9e547-2794-424a-bea9-74fe56e6eb34'
SELECT * FROM "users" WHERE id = '01578c9e-8e76-46a4-b2b2-50788cec2ccd' ORDER BY "users"."id" LIMIT 1
SELECT * FROM "organizations" WHERE id = 'd0a9e547-2794-424a-bea9-74fe56e6eb34' ORDER BY "organizations"."id" LIMIT 1
SELECT * FROM "devices" WHERE public_key = 'tqdJitNmvAkHuePEqbx2p5ITJekVcM3o6FKQiy/fCi0=' ORDER BY "devices"."id" LIMIT 1
INSERT INTO "devices" …

perf: run fewer SQL statements to create a device.

---

.github/workflows/deploy.yml
deploy/apex/base/apiproxy/deployment.yaml
deploy/apex/base/backend-web/deployment.yaml
deploy/apex/overlays/prod/kustomization.yaml
deploy/apex/overlays/prod/serviceaccount.yaml
deploy/apex/overlays/qa/files/apex.json
deploy/apex/overlays/qa/kustomization.yaml
deploy/apex/overlays/qa/serviceaccount.yaml

Commit makes following changes:
* Augment allowPrevilegeEscalation for apiproxy container to handle openshift security contexts
* Fixed auth ingress to use ImplementationSpecific PathType to allow route.openshift.io/termination: passthrough
* Fix prod overlay OIDC provider url and Certificate dnsNames & issuerRef/Name.
* Fix deploy job's to update the newTag of the correct ipam image.
Signed-off-by: greg pereira <grpereir@redhat.com>
Co-authored-by: Anil Kumar Vishnoi <avishnoi@redhat.com>

Production and QA deployment of  Apex service on ROSA cluster

---

Makefile

to make it easy to inspect the apiserver DB with SQL commands.

fix: add a `make run-sql-apiserver` target 

---

.github/workflows/build.yml
.github/workflows/promote.yml
.github/workflows/qa-ec2.yml
.gitignore
.vscode/settings.json
Makefile
hack/nexodus-installer.sh
hack/update-ca.sh
ops/ansible/README.md
ops/ansible/aws/vars.yml
ops/ansible/azure/vars.yml
ops/ansible/gcp/vars.yml
package-lock.json

Fix binaries artifacts name in build job and scripts 
Fix namespace name in makefile for run-sql-apiserver target
Fix apexd references in ansible vars/readme

Remove remaining apex-net s3 bucket references from the code

---

.dockerignore
.gitignore
Makefile

that uses telepresence to allow you to run the apiserver in a local debugger.

feat: add a `make debug-apiserver` target 

---

integration-tests/integration_test.go
internal/handlers/device.go

- Resolves #522
- Re-enables nexctl e2e #437

Fix IPAM pool releasing and the related e2e

---

hack/api-token.sh
internal/docs/docs.go
internal/docs/swagger.json
internal/docs/swagger.yaml
internal/handlers/user.go
internal/models/user.go
internal/routers/middleware.go

This gets the last of the apex references in code.

internal: Drop remaining apex references

---

.github/workflows/qa-ec2.yml
ops/ansible/aws/deploy-hub-router/tasks/main.yml
ops/ansible/aws/deploy-mesh/tasks/main.yml

- relevant actions.secrets have been updated as well.

ec2-qa updates

---

Makefile

Allow showing the commands run when working against the kind-based development environment. This is helpful to determine which command results in a given failure. Some other targets were updated while I was at it.
To see all of the commands, set NOISY_BUILD with something like this:
$ NOISY_BUILD=y make recreate-db

Makefile: Allow showing commands for kind env

---

deploy/nexodus/overlays/prod/files/nexodus.json
deploy/nexodus/overlays/prod/realm.yaml

This isn't fully working, so let's disable it in prod so people don't click it just to get an error.

prod: Disable the github provider

---

deploy/nexodus/overlays/prod/files/nexodus.json
deploy/nexodus/overlays/qa/files/nexodus.json

file because it doesn't allow comments in the json file

Keycload will throw error while parsing nexodus.json

---

.github/workflows/promote.yml
deploy/nexodus/overlays/prod/kustomization.yaml

job can update the newTag of correct ipam image from quay.io

Fix ipam image name, so that promote

---

cmd/nexctl/local.go
integration-tests/integration_test.go
integration-tests/util_test.go

- Replaces sleeps for discovery node joins with nexctl nexd status

Add e2e coverage for nexctl socket status

---

integration-tests/util_test.go
internal/util/run_periodically.go
internal/util/run_periodically_test.go

commit f3dad78726f4da4383df201505f00ff24997f52c
Date:   Sat Mar 11 21:53:11 2023 -0500
e2e: Use CheckPeriodically() when waiting on nexd status
commit 1afea97a72f63881c010724c647a8d0e1a21b119
Date:   Sat Mar 11 21:39:45 2023 -0500
util: Add CheckPeriodically()
Add a new utility function, CheckPeriodically(). Adjust
RunPeriodically() to be a simpler wrapper around the new function.
CheckPeriodically() can be used to periodically check for a condition to
become true. It can also return an error.

Add a new CheckPeriodically() util helper

---

.github/actions/setup-go-env/action.yaml
.github/workflows/build.yml
Makefile
go.mod
go.sum
hack/install-tools.sh
internal/util/run_periodically_test.go
kind-images.lock

- drys up the build.yml 
- try to do more steps in parallel 
- cache more to speed things up

feat: simplify the CI workflow 

---

internal/nexodus/nexodus.go

- Initializes a new OIDC client in the case where the token becomes invalid.
This includes surpassing the keycloak offlineSessionIdleTimeout timer.
- If the onboard was via the one-time pass, exit with a message instead
of prompting with a url in the logs.
- The offlineSessionIdleTimeout default value is 30 days, so it is not an
error that will be triggered often for one-time joiners.
- In testing so far, the existing OIDC keycloak handles reconnects quite
well as is, as long as offlineSessionIdleTimeout is not eclipsed.

Add agent reconnects in the case of invalid token grants

---

deploy/nexodus/base/auth/certificate.yaml

This will solve some sync issues within ArgoCD
/cc @Gregory-Pereira

Fixes some current issues with argo

---

.github/workflows/build.yml
Makefile

try to implement a better wait condition for the crunchy postgres to be up
try to enable cockroach based e2e

chore: start the image builds sooner to speed up PR build times

---

go.mod
go.sum
integration-tests/integration_test.go
integration-tests/util_test.go

We now create test users on the fly with keycloak admin apis.

feat: run some of the e2e tests in parallel

---

internal/nexodus/ctlserver_linux.go

This commit fixes a couple of problems in exit handling from the unix socket control server.
First, the code mistakenly did a Done() on a waitgroup instead of Wait(). This caused a panic in a case where no subroutines were ever started due to lack of permissions to open the socket.
With this fixed, it exposed that the server was not exiting properly when the context was canceled. The listener routine needed to skip trying to return its error when everything was shutting down.
Finally, if the control server does exit with an error, such as having insufficient permissions to open the socket. It was trying to restart it in a busy loop. This adds a sleep to rate limit it. When running with insufficient permissions, you'd see this retry many, many times before the rest of nexd figured out that …

nexd: Fix mistakes in ctlserver exit handling

---

deploy/nexodus/overlays/prod/files/nexodus.json
deploy/nexodus/overlays/qa/files/nexodus.json

This fixes the config drift introduced by #624

deploy: Update keycloak config for qa/prod

---

internal/nexodus/nexodus.go
internal/nexodus/stun.go

- If the first STUN lookup fails, return an error rather than moving on to the second.
- Changed logging to debug and added a more descriptive output to the error.

Add error handling to symmetric NAT checks

---

cmd/nexd/main.go
docs/development/design/nexodus-connectivity.md
docs/user-guide/user-guide.md
integration-tests/integration_test.go
internal/database/database.go
internal/database/migration_20230126_0000/20230126-0000.go
internal/database/migration_20230321_0000/20230321-0000.go
internal/docs/docs.go
internal/docs/swagger.json
internal/docs/swagger.yaml
internal/handlers/device.go
internal/models/device.go
internal/nexodus/nexodus.go
ops/ansible/aws/deploy-hub-router/tasks/main.yml

- Details in issue #610
- Example output in the PR comments.

Break up --hub-router into discovery and relay

---

docs/development/design/TEMPLATE.md
docs/development/design/authorization.md
docs/development/design/cockroachdb.md
docs/development/design/project-name.md
docs/development/design/rate-limiting.md

The template included the incorrect URL template for issues. This URL also made it into several design docs, so fix all of them.

docs: Fix issues URL in template

---

deploy/nexodus/base/apiproxy/files/envoy.yaml

Increase configured envoy timeouts.

fix: sporadic 503 where occurring

---

docs/development/design/userspace-mode.md

I forgot to set a proper title in this file. Oops.

docs: Fix design doc title

---

cmd/nexd/main.go

This moves the run code into its own function that can be
paramterized. This will be used when adding subcommands that alter the
behavior.
Also remove some code that was a placeholder and never implemented.
This cleanup probably belongs elsewhere anyway. It's going to be
dependent on the mode nexd is running in, the OS, and eventually the
tunneling mechanism.

nexd: Move run code into its own function

---

docs/development/design/dual-stack.md.md

Dual Stack design doc

---

integration-tests/integration_test.go

- Cleanup the commented e2e block with a user delete and validation

Fixup tests post-schema change and validate user deletes

---

.gitattributes
.github/workflows/build.yml
Makefile
cmd/nexctl/local_unix.go
internal/nexodus/ctlserver_unix.go
internal/nexodus/ctlserver_windows.go
ui/src/pages/Dashboard.tsx

add .gitattribute file to handle checking out code on Windows better. 
give .exe suffix to windows binaries.

feat: add unix socket support for windows build

---

integration-tests/integration_test.go

Add pings between the two nodes before exercising the nexd proxy functionality. This establishing whether basic L3 connectivity is established to differentiate between broken proxy handling or a failure prior to getting that far.
Also tweak the message when `curl` fails, as it's an expected condition if it starts too fast before peering has finished.

e2e: Add pings to proxy tests

---

Containerfile.test
docs/development/design/nexodus-connectivity.md
internal/nexodus/nexodus.go
internal/nexodus/wg-iface.go
internal/nexodus/wg-peers.go
ops/ansible/aws/deploy-hub-router/tasks/main.yml
ops/ansible/aws/deploy-mesh/tasks/main.yml

- also resolves an observed ip6tables issue in fedora containers

Replaces iptables with nftables

---

Makefile

Update how make determines whether docs and code generators need to run.
By using the touched file method, these were running more than they
should. They should only run if their source is newer than their output.
Since these processes have both sources and outputs that are files, we
should be using them.
This fixes some errors I was having running parallel make. In
particular, `go mod tidy` was running at the same time as the client api
code generator, which would break. At least in this case, the code
generator shouldn't be running at all.

Makefile: Update generator dependency handling

---

Makefile

Cache most of the chroot used to build rpms in a container image that is prebuilt and pushed to quay.io.
Closes #746

ci: Speed up rpm builds in CI

---

integration-tests/integration_test.go
integration-tests/users-api.feature
internal/database/database.go
internal/database/migration_20230411_0000/20230411-0000.go
internal/handlers/user.go
internal/models/base.go
internal/models/user.go

* a deleted user can now be enabled again if he logs back into the API.

feat: enable soft deletes, add more db indexes

---

internal/database/database.go
internal/database/migration_20230413_0000/20230413-0000.go

We need a fresh DB state now that KC is persisting user ids.

fix: add a migration to reset the DB.

---

ops/ansible/aws/deploy-mesh/tasks/main.yml
ops/ansible/aws/deploy-relay/tasks/main.yml

- Improves artifact logs readability.

Add unique naming for relay and symmetric only artifacts

---

.github/workflows/dev-ec2.yml
ops/ansible/aws/deploy-mesh/tasks/main.yml
ops/ansible/aws/deploy-relay/tasks/main.yml

bug-fix #822 playbook error with --relay-node launch

---

internal/docs/docs.go
internal/docs/swagger.json
internal/docs/swagger.yaml
internal/handlers/invitations.go
internal/models/invitation.go
internal/routers/routers.go
ui/src/App.tsx
ui/src/pages/Invitations.tsx

* added a GET api path to get a single invitation
* support creating an invitation by user name.

feat: add an invitations resource to manage org invitations.

---

README.md
docs/quickstart.md
ui/src/pages/Dashboard.tsx

Add the simplest, quickest way to get up and running with Nexodus.
Update the UI dashboard to refer to this new quick start guide.
Closes #649

docs: Add Quick Start

---

docs/deployment/deployment.md

Save these in our docs for convenience.

docs: Add links to prod/qa cluster resources

---

README.md

Set up a place for live discussion. Discord was chosen as a free hosted option that does not limit history.
Closes #847

README.md: Add Discord link

---

Containerfile.nexd
cmd/nexd/main.go
integration-tests/proxy_test.go
internal/nexodus/nexodus.go
internal/nexodus/userspace_proxy.go

commit 74e74d23ac257be5b3d5ba9781027870744f3325
Date:   Thu Apr 20 14:08:47 2023 -0400
nexd: Add proxy config validation
Do validation on proxy rules at startup. Add an e2e test that
validates various error cases.
commit 39aea4b2729b3db7b39474ee8b759965d8cd5da5
Date:   Thu Apr 20 14:07:23 2023 -0400
nexd: Reorder build steps to improve layer caching
I noticed that every build was re-running `go mod download`. This
reordering seems to get it to keep that portion cached.

nexd: Add proxy config validation

---

internal/nexodus/ctlserver_unix.go

If nexd fails to open its socket for the ctlserver, it will now exit. Previously if it failed for some reason (like nexd was already running and listening on this socket), it would just contiously print the error.
If it fails after previously working, `nexd` will stay up and try to recover the ctlserver interface.

nexd: Exit if ctlserver can't start

---

internal/nexodus/nexodus.go

- This will let us know if the error is coming from envoy is elsewhere

Add http headers to debugs in the case of nexd API call failures

---

MAINTAINERS.md
docs/deployment/nexodus-service.md

Added more to validating the stack

Added a bit to the kind quickstart doc

---

internal/nexodus/nexodus.go

- Response header needed to be nil checked to avoid a segfault in the case where the token is invalid and no repsonse header is received.
- Added checks for both invalid_grant and invalid_token to give a user message on how to resolve the token error.
- The checks both error messages because when you swap api-servers using a token for another server, the first error message you get is invalid_token and all subsequent messages are invalid_grant in that order.

Handle token issues when swapping api-servers

---

integration-tests/proxy_test.go

I'm seeing failures in this test in CI that I have not been able to
reproduce locally. In the failure case, a test case will return without
an error. Add logging of any output returned in case that gives any
hints.
I also refactored the test to DRY it up.
Related to #960 

e2e: Add logging to TestProxyInvalidConfig

---

integration-tests/proxy_test.go
internal/nexodus/ctlconnectivty.go
internal/nexodus/keepalive.go

Add support for connectivity probes when running `nexd` in `proxy` mode.
It needs to use the userspace stack for sending/receiving ICMP in this
case.
After this change, you can run `nexctl connections` for `nexd proxy`.

nexd: Fix connectivity probes for proxy mode

---

ops/ansible/aws/deploy-mesh/tasks/main.yml
ops/ansible/aws/deploy-relay/tasks/main.yml
ops/ansible/aws/qa/qa-deploy-mesh/tasks/main.yml
ops/ansible/aws/qa/qa-deploy-relay/tasks/main.yml

- Add mode details to the artifact results. Adds a bit more convergence
time to get better logs for when we bump to higher device counts.
- Removes some noise from the stdout by dumping to the logs only
in some cases.

Scale testing tweaks

---

deploy/nexodus-monitoring/overlays/rosa/kustomization.yaml
deploy/nexodus-monitoring/overlays/rosa/monitoringstack.yaml

deploy: Add MonitoringStack for ROSA

---

deploy/nexodus-monitoring/base/grafana/apiserver-dashboard.yaml

grafana: Add a pretty chart for API requests

---

.dockerignore
deploy/nexodus/overlays/prod/kustomization.yaml
deploy/nexodus/overlays/qa/kustomization.yaml

... and ignore some more things in the docker context to hopefully avoid posioning the cache.

deploy/rosa: Allow use of privileged scc

---

internal/api/public/api_devices.go
internal/api/public/api_invitation.go
internal/docs/docs.go
internal/docs/swagger.json
internal/docs/swagger.yaml
internal/handlers/device.go
internal/handlers/fflags.go
internal/handlers/invitations.go
internal/handlers/organization.go
internal/handlers/user.go

Looks like the annotation is `@Accept` instead of `@Accepts` to generate the application/json consumer content types for OpenAPI.

Change the @Accepts field to @Accept in handler

---

docs/user-guide/scenarios/nexd-proxy-in-kube.md

This change includes an explanantion of demo3, originally described in
the nexlink design proposal. This completes the documentation of the
proposed demo scenarios from that design.

docs: Document proxy-in-kube demo3

---

.github/workflows/qa-scale-containers.yml

- This will give the job access to the quay robot credentials

Add image-repositories env to the containerized scale qa

---

deploy/nexodus/overlays/released/kustomization.yaml
docs/development/design/security-groups.md

Network policy design doc

---

cmd/nexd/main.go
deploy/nexodus/base/apiserver/deployment.yaml
deploy/nexodus/base/apiserver/kustomization.yaml
deploy/nexodus/overlays/dev/kustomization.yaml
docs/user-guide/agent.md
integration-tests/integration_test.go
internal/fflags/fflags.go
internal/handlers/organization.go
internal/handlers/organization_test.go
internal/nexodus/join.go
internal/nexodus/nexodus.go
internal/nexodus/wg_peers.go
ui/src/App.tsx
ui/src/pages/Organizations.tsx

- nexd: Fix relay of non-default CIDRs
- nexd: Support choosing an organization
commit 410d68231fc8b2da2ec74897b1915cf83bd93136
Date:   Sat May 27 08:48:45 2023 -0400
nexd: Fix relay of non-default CIDRs
nexd assumed that the valid CIDRs for a relay were the default CIDRs.
Relays wouldn't have worked for an organization with non-default
CIDRs.
commit 7c7385a7b16d4697f5b7b8f90ca7ce755a197751
Date:   Fri May 26 21:13:01 2023 -0400
nexd: Support choosing an organization
By default, nexd will pick the organization for you as long as the
user is only a member of a single organization. Otherwise, an
organization must be specified as a command …

Allow nexd to choose an organization to connect to

---

ui/src/pages/Login.tsx

- remove the legacy apex background from the login page

Remove the UI login background img

---

internal/nexodus/nexodus.go
internal/nexodus/wg_peers.go

This change should introduce no functional changes, but it reorganizes the code in an important way.
Previously, the only time `nexd` would reconfigure its peers is when it saw a configuration change come in for that peer from the API. The logic is now changed such that the peer will be configured anytime that nexd's peer configuration calculations decide. It may change based on a config change from the API, or it may change because `nexd` decides it should change for some other reason.
A future change will take advantage of this shift to start making peer configuration changes based on nexd's own observations on the connection health to that peer.
Part of #965

nexd: Allow nexd to change peer configs

---

Containerfile.nexd

nexd: Add bash tab completion to container image

---

cmd/nexd/main.go
docs/user-guide/nexd-proxy.md
go.mod
hack/udpong/udpong.go
integration-tests/helper_test.go
integration-tests/proxy_test.go
internal/nexodus/ctlserver.go
internal/nexodus/nexodus.go
internal/nexodus/proxyrule.go
internal/nexodus/userspace_proxy.go

proxy: support simple client-side load balancing for proxy mode

---

cmd/nexd/main.go

Closes #1152
Added a custom zap custom configuration to remove `ts` from the logs

added custom zap logger config

---

.github/workflows/qa-dev.yml
.github/workflows/qa-scale-containers.yml
.github/workflows/qa-scale.yml

- If nexd failed to start this will fail the test.

Add an additional fail parameter for QA.

---

hack/install-tools.sh

hack: Add kubectl to install-tools.sh

---

internal/nexodus/nexodus.go
internal/nexodus/nexodus_darwin.go
internal/nexodus/nexodus_linux.go
internal/nexodus/nexodus_userspace.go
internal/nexodus/nexodus_windows.go

resolving a part of issue #1187

renames ax to nx on all the /internal/nexodus/nexodus*.go files

---

CONTRIBUTING.md

CONTRIBUTING.md: Add link to pull-requests doc

---

internal/nexodus/keys.go
internal/nexodus/keys_darwin.go
internal/nexodus/keys_linux.go
internal/nexodus/keys_windows.go

renames ax to nx in the receiver functions of internal/nexodus/keys*.go files

---

cmd/nexctl/device.go
cmd/nexctl/main.go

Add a full and partial display for columns in nexctl device lists

---

internal/handlers/organization.go
internal/handlers/user.go

Moving create default security group logic into transaction and removing the manual error handling that was previously done.
Closes https://github.com/nexodus-io/nexodus/issues/1131

Create organization sg transaction

---

cmd/nexd/main.go
docs/deployment/nexodus-service.md
docs/development/design/userspace-mode.md
docs/quickstart.md
docs/user-guide/agent.md
docs/user-guide/discovery-and-relay.md
docs/user-guide/nexd-proxy.md
docs/user-guide/scenarios/nexd-proxy-in-kube.md
hack/update-ca.sh
integration-tests/helper_test.go
internal/handlers/organization.go

and deprecate configuring it via a positional argument.

nexd: configure the service-url using a flag 

---

docs/development/design/device-metadata.md

docs: Propose API support for device metadata

---

internal/nexodus/join.go
internal/nexodus/nexodus.go

Addressing: https://github.com/nexodus-io/nexodus/issues/1063

Switching device registration log for newly register device and re-connecting devices

---

Containerfile.apiserver
Makefile
cmd/apiserver/main.go
cmd/apiserver/pprof_disabled.go
cmd/apiserver/pprof_enabled.go
docs/development/debugging.md

Also document how to get a profile from a running apiserver.

Add pprof support to the apiserver image

---

.github/workflows/build.yml
Makefile
hack/install-tools.sh

It will only show test output of failed tests, and display them non-interleaved.

tests: use gotestsum to reduce tests output verbosity.

---

cmd/apiserver/main.go
go.mod
internal/handlers/api.go
internal/handlers/handlers_test.go
internal/handlers/user.go

Using redis to cache the user
closes: https://github.com/nexodus-io/nexodus/issues/1191
closes: https://github.com/nexodus-io/nexodus/pull/1236

Cache user to improve performance of createUserIfNotExists

---

internal/handlers/organization.go

I got a 500 error creating a new organization in my development
environment. This commit addresses a couple of issues I found while
looking into this.
1. Ensure that the default IPAM namespace has been created. The 500
error I hit was because it didn't exist. It gets created when a
user first logs in. Since this was an existing environment, I
wasn't going through that code path. Now this code does the same
thing and ensures it exists.
2. Once it worked, I noticed that the security group ID was empty in
the result I received from the API. Fix the code to put the
security group ID on the org result returned from the API.
3. Add error logging that I put in place to see what was causing my
first error.

api: Fix a couple of issues with org create

---

internal/handlers/organization.go

Address issues: https://github.com/nexodus-io/nexodus/issues/1185

release prefix for cidrv6 when deleting org

---

ops/ansible/aws/qa/qa-containers-deploy-mesh/tasks/main.yml
ops/ansible/aws/qa/validate-connectivity-qa-containers/tasks/main.yml

- Update the nexctl commands for container runs

Update the qa-containers image to quay.io/nexodus

---

docs/development/scale-testing.md
hack/e2e-scripts/qa-container-scale.sh

Add a script for spinning up containers against qa outside of CI

---

integration-tests/kube_test.go

Wait for the pod to be deleted before trying to get the new pod info.

e2e: improve kube test reliability

---

deploy/nexodus/base/apiproxy/deployment.yaml
deploy/nexodus/base/apiproxy/kustomization.yaml
deploy/nexodus/overlays/dev/kustomization.yaml
deploy/nexodus/overlays/prod/kustomization.yaml
deploy/nexodus/overlays/qa/kustomization.yaml

*.* Disable apiproxy and apiserver debug in production deployment 
*.* Increase the postgres pgdata to 6Gi for production and 4Gi for QA

Update deployment yamls to

---

hack/e2e-scripts/qa-container-scale.sh
hack/e2e-scripts/qa-kind-container-scale.sh

*.* Label containers with user id, so that multiple instances of the
script can be run and container belongs to each user can be identified
through label
*.* Add deployment flag to switch the URLs as per the deployment
environment, rather than changing it manually everytime.
*.* Fixing comments and usage text

Update scale script to

---

docs/quickstart.md
docs/user-guide/network-routers.md

- Also adds container instructions for network router

Added windows instructions in the docs  quick start

---

hack/e2e-scripts/scale/check-connectivity.sh
hack/e2e-scripts/scale/check-errors.sh
hack/e2e-scripts/scale/qa-container-scale.sh

Also fixed minor typos and permission issues

Take number of orgs in the scale script to create multiple orgs.

---

internal/nexodus/route_windows.go
internal/nexodus/utils_windows.go

- Moving error logging to debug for the issue described in #1362
- Moved a couple of methods to the windows routing grouping

More windows route logging cleanup

---

integration-tests/integration_test.go
internal/nexodus/keys.go
internal/nexodus/nexodus.go
internal/nexodus/utils_darwin.go
internal/nexodus/utils_linux.go
internal/nexodus/utils_windows.go

- removing the deprecated legacy key management

Remove legacy keys and locations

---

cmd/nexctl/main.go
ui/src/pages/Users.tsx

- Also hides the delete flag in nexctl

Remove delete user from the UI

---

hack/e2e-scripts/aws-e2e-pr-build.yml

- Debugging qa-dev workflow job failures

Convert qa-dev init script to Ansible

---

internal/nexodus/wg_peers.go

Define more concretely the concept of a peering method. Each method
has a name, a set of prerequisites that must be met to use it, and an
implementation of generating wireguard configuration using that
method.
There should be no functional changes other than an updated debug log
message that will now indicate which peering method is in use for a
peer.

nexd: Refactor peering method choices

---

Containerfile.apiserver
Containerfile.nexd
Makefile

Usage: `NEXODUS_RACE_DETECTOR=1 make ...`

feat: support building nexd and the apiserver with the go race detector

---

deploy/nexodus/overlays/prod/kustomization.yaml

This reverts commit 71a117cb2a6844175e334d7ff51b68a0c94947d0.
This didn't help with the issue I'm looking at.

Revert "deploy: Enable apiserver debug in prod"

---

.github/workflows/qa-dev.yml
ops/ansible/aws/deploy-ec2-qa.yml
ops/ansible/aws/qa/validate-connectivity-qa-containers/tasks/main.yml

qa-dev: dump connectivity test info for all nodes

---

integration-tests/api_test.go
integration-tests/features/device-api.feature
internal/api/public/api_organizations.go
internal/api/public/api_organizations_custom.go
internal/api/public/model_models_device.go
internal/database/database.go
internal/database/migration_20230921_0000/20230921-0000.go
internal/docs/docs.go
internal/docs/swagger.json
internal/docs/swagger.yaml
internal/handlers/api.go
internal/handlers/events.go
internal/handlers/fetchmgr/envfm/envfm.go
internal/handlers/online_tracker.go
internal/handlers/user.go
internal/models/device.go
internal/nexodus/nexodus.go
internal/state/fstore/fstore.go
internal/util/getenv.go

by tracking if it has an active long poll request against the events endpoint.

feat: apiserver will now track a device’s online status 

---

deploy/nexodus/overlays/playground/kustomization.yaml
deploy/nexodus/overlays/prod/kustomization.yaml
deploy/nexodus/overlays/qa/kustomization.yaml

Enable security groups feature for prod/qa/playground

---

Makefile

Makefile: don't assume .certs dir exists

---

ops/ansible/aws/deploy-ec2.yml

qa-dev: Run connectivity check on all nodes

---

ui/package.json
ui/src/pages/SecurityGroups/SecurityGroupEditRules.tsx
ui/src/pages/SecurityGroups/SecurityGroupTable.tsx

- Specify: Source IP Ranges || Destination IP Ranges

Add more clarity to IP Range SG labels

---

ui/src/providers/AuthProvider.tsx

- Will help chase down a return to login page issue after ~24hrs. Need to see why it hangs instead of cleanup() returning it to the login.
```
Error refreshing the token: undefined index-0a6f749d.js:273:26844
Received 401 from server during token fetch. index-0a6f749d.js:273:22794
Failed to refresh the token. index-0a6f749d.js:273:23664
Error refreshing the token: undefined index-0a6f749d.js:273:26844
Login Error index-0a6f749d.js:273:25394
Clearing refresh interval index-0a6f749d.js:273:24148
Cleanup Called index-0a6f749d.js:273:24429
Uncaught (in promise) Error: 
```

Add UI logging for an uncaught error

---

Makefile

that will reconnect you (needed if you upgrade your telepresence version)

Added a `make telepresensec-connect-f` target 

---

contrib/rpm/nexodus.spec.in

rpm: depend on nftables

---

integration-tests/features/events-api.feature
integration-tests/routing_test.go
internal/handlers/security_group.go

added a feature tests for the security group events.

apiserver: Fix bug where security-group events were not being sent on security group updates.

---

cmd/nexctl/device.go
integration-tests/features/device-api.feature
internal/api/public/model_models_update_device.go
internal/docs/docs.go
internal/docs/swagger.json
internal/docs/swagger.yaml
internal/handlers/device.go
internal/models/device.go

Also, make all fields of the device update optional so you can pick and choose which fields to patch.

nexctl: support updating a device to change the hostname or security-group

---

go.mod
go.sum

deps: move from my fork of github.com/mhmtszr/concurrent-swiss-map 

---

internal/cucumber/http_response.go
internal/docs/docs.go
internal/docs/swagger.json
internal/docs/swagger.yaml
internal/handlers/reg_key.go
internal/routers/routers.go

commit 71f4cb8e416aa800a44040aee71cd74f7d507453 (HEAD -> openapi-work, chirino/openapi-work)
Author: Hiram Chirino <hiram@hiramchirino.com>
Date:   Tue Nov 7 19:48:17 2023 -0500
Move the certs endpoints under the Auth grouping of api endpoints.
Signed-off-by: Hiram Chirino <hiram@hiramchirino.com>
commit 96bf5eb4b58029d071b8fe51769a08f953c056c0
Author: Hiram Chirino <hiram@hiramchirino.com>
Date:   Tue Nov 7 19:45:33 2023 -0500
fix: Make sure the openapi doc linked from the console the right Host and Scheme set on it.
Also do better verification of content type in the feature tests.
Signed-off-by: Hiram Chirino <hiram@hiramchirino.com>

Openapi work

---

cmd/nexctl/device.go
cmd/nexctl/vpc.go

This option went boom because of fields that no longer exist.

nexctl: Fix device list --full

---

internal/nexodus/nexodus.go

Handle the case when the security group Id is changed for the local
device. Prior to this change, it would be ignored until another field
changed on the Device. This was because the deviceUpdated() method did
not check the security group Id.
Some additional handling was required to ensure that the security
group update caused an immediate reconcile of the security group
settings, since that happens outside of the device reconcillation
method.
In passing, take deviceUpdated() off of the Nexodus struct, as it
didn't use anything from there.

nexd: Handle when sec group Id changes on Device

---

cmd/nexctl/vpc.go
integration-tests/features/vpc-api.feature
internal/handlers/vpc.go
internal/util/ip_utils.go

Adds api feature tests for this scenario.

fixes: #1631 500 response on an invalid VPC CIDR

---

internal/fflags/fflags.go
internal/handlers/api.go
internal/handlers/fflags.go
internal/handlers/invitations_test.go
internal/handlers/organization.go
internal/handlers/reg_key.go
internal/handlers/security_group.go
internal/handlers/security_group_test.go
internal/handlers/vpc_test.go

cleanup: simplify feature flag checks.

---

integration-tests/integration_test.go
internal/handlers/user.go

Added e2e to prevent this breaking in the future.

fix: admin login was not working.

---

.github/workflows/build.yml
.github/workflows/deploy.yml
Makefile

rpm: Enable Fedora 39 builds

---

deploy/nexodus/overlays/playground/kustomization.yaml
deploy/nexodus/overlays/prod/kustomization.yaml
deploy/nexodus/overlays/qa/kustomization.yaml

This was breaking reg key logins.

fix: deployment configs to point at the right API URL.

---

.github/workflows/deploy.yml

- Calls the ppa-build.yml workflow from deploy.

Add the PPA/deb build dispatch to the deploy workflow

---

Makefile
cmd/nexctl/invitation.go
integration-tests/features/invitation-api.feature
integration-tests/util_test.go
internal/api/public/model_models_add_invitation.go
internal/api/public/model_models_invitation.go
internal/database/database.go
internal/database/migration_20231130_0000/migration.go
internal/docs/docs.go
internal/docs/swagger.json
internal/docs/swagger.yaml
internal/handlers/handlers_test.go
internal/handlers/invitations.go
internal/handlers/user.go
internal/models/invitation.go
internal/models/user_identity.go
internal/routers/middleware.go
ui/src/pages/Invitations.tsx

Update the invitation’s api to use email address vs usernames to invite users.

feat: add a user_identities table to track user emails

---

cmd/nexctl/connectivity.go
cmd/nexctl/exit_node.go
cmd/nexctl/local_unix.go
cmd/nexctl/main.go
cmd/nexctl/peers.go
docs/user-guide/nexctl.md
go.mod
internal/api/nexctl.go
internal/nexodus/ctlconnectivty.go
internal/nexodus/keepalive.go

* avoids importing the full internal/nexodus package into nexctl.
* we removed the remaining vestiges of the tabwritter

nexctl: reduce binary size, add yaml support, table format all list results

---

internal/api/public/model_models_user_info_response.go
internal/docs/docs.go
internal/docs/swagger.json
internal/docs/swagger.yaml
pkg/oidcagent/handlers.go
pkg/oidcagent/models/models.go
ui/src/pages/Invitations.tsx
ui/src/providers/AuthProvider.tsx

- Adds the custom fetch handler since it's beyond what react-admin can handle.

Add accept invitations to the UI

---

cmd/apiserver/main.go
cmd/apiserver/pprof_disabled.go
cmd/apiserver/pprof_enabled.go
cmd/nexctl/connectivity.go
cmd/nexctl/device.go
cmd/nexctl/device_metadata.go
cmd/nexctl/exit_node.go
cmd/nexctl/invitation.go
cmd/nexctl/local_unix.go
cmd/nexctl/main.go
cmd/nexctl/organization.go
cmd/nexctl/peers.go
cmd/nexctl/reg_key.go
cmd/nexctl/security_group.go
cmd/nexctl/user.go
cmd/nexctl/vpc.go
cmd/nexd/main.go
cmd/nexd/pprof_disabled.go
cmd/nexd/pprof_enabled.go

In v3 the Action fn signature is: `func(ctx context.Context, command *cli.Command) errror` Refactor exiting handlers to be more compatible when we switch to it.

prep for urfave/cli/v3

---

cmd/apiserver/main.go
cmd/apiserver/pprof_disabled.go
cmd/apiserver/pprof_enabled.go
cmd/nexctl/connectivity.go
cmd/nexctl/device.go
cmd/nexctl/device_metadata.go
cmd/nexctl/exit_node.go
cmd/nexctl/invitation.go
cmd/nexctl/local_unix.go
cmd/nexctl/main.go
cmd/nexctl/organization.go
cmd/nexctl/peers.go
cmd/nexctl/reg_key.go
cmd/nexctl/security_group.go
cmd/nexctl/user.go
cmd/nexctl/vpc.go
cmd/nexd/flags_unix.go
cmd/nexd/main.go
cmd/nexd/pprof_disabled.go
cmd/nexd/pprof_enabled.go
docs/user-guide/nexctl.md
docs/user-guide/nexd.md
go.mod
go.sum
hack/e2e-scripts/kctool/kctool.go
internal/nexodus/ctlstatus.go
pkg/oidcagent/cmd/go-oidc-agent/main.go
pkg/oidcagent/examples/apiserver/main.go

* upgrade from urfave/cli/v2 to urface/cli/v3

cli: support persistent options on global flags of the cli commands.

---

deploy/nexodus-monitoring/base/grafana/apiserver-dashboard.yaml
deploy/nexodus-monitoring/base/grafana/datasource.yaml
deploy/nexodus-monitoring/base/grafana/grafana.yaml
deploy/nexodus-monitoring/overlays/rosa/grafana-patch.yaml
deploy/nexodus-monitoring/overlays/rosa/kustomization.yaml
deploy/nexodus-monitoring/overlays/rosa/monitoringstack.yaml

This reverts commit b7b3b2bce636710669182cf1a1b84d20e45aa93c.

Revert "Upgrade the graphana api version to v1beta1"

---

.github/workflows/qa-dev.yml
hack/e2e-scripts/aws-e2e-pr-build.yml

Adds retries to recreate-db and unpins ansible-core version

qa-dev tshooting of ansible unreachables

---

.github/workflows/qa-dev.yml
hack/e2e-scripts/aws-e2e-pr-build.yml

- Also removing the make library for debugging  recreate-db

Turn up verbose logging for qa-dev

---

ops/ansible/aws/ansible.cfg

- Increase control persist to 10m
- Explicitly disable pipelining
- Add retries

Adjust ansible cfg

---

hack/e2e-scripts/aws-e2e-pr-build.yml

Explicitly set the python var

---

ui/package-lock.json
ui/package.json
ui/src/layout/Menus.tsx

Add missing prop to MenuItemLink after react-admin bump

---

package-lock.json

- Likely slid in from an errant nom install outside of the ui dir.

Remove the package-lock from the root dir

---

integration-tests/features/device-api.feature
internal/api/public/model_models_update_device.go
internal/docs/docs.go
internal/docs/swagger.json
internal/docs/swagger.yaml
internal/handlers/device.go
internal/models/device.go
internal/nexodus/join.go

Update relay status if device rejoins as a relay

---

.github/workflows/deploy.yml
deploy/nexodus/base/apiserver/kustomization.yaml
deploy/nexodus/overlays/dev/kustomization.yaml
deploy/nexodus/overlays/playground/kustomization.yaml
deploy/nexodus/overlays/prod/kustomization.yaml
deploy/nexodus/overlays/qa/kustomization.yaml
ui/src/App.tsx
ui/src/common/FlagsContext.tsx
ui/src/layout/Layout.tsx
ui/src/layout/Menus.tsx
ui/src/pages/Devices.tsx
ui/src/pages/RegKeys.tsx
ui/src/pages/VPCs.tsx

* Make sure the security groups feature flags are set correctly for our different deployments.  
* ci: Don’t deploy the playground branch anymore since it’s been merged into main.

ui: don’t show security group fields when that feature flag is off

---

internal/routers/token.rego

This reverts commit dfdfb7be461bc3472670cac1835ebe0f09106151.

Don't restrict google logins to redhat.com email addresses

---

docs/policies.md

docs: Add a link to the red hat privacy policy

---

.github/workflows/promote.yml

Add a unique artifact name to resolve this promote error:
https://github.com/nexodus-io/nexodus/actions/runs/7659274653/job/20874667851

Resolve artifact@v4 issue

---

.github/workflows/promote.yml

Attempt to resolve https://github.com/nexodus-io/nexodus/actions/runs/7669568833/job/20904488575

Add a github token env to promote

---

.github/workflows/promote.yml

Reference: https://github.com/actions/checkout#usage

Add a token for checkout@v4

---

docs/development/design/derp-relay.md
docs/user-guide/nexd.md

Added design document for DERP relay integration

---

docs/development/code-organization.md
docs/development/index.md

- docs: Add docs/development/index.md
- docs: Add an overview of code organization

doc: Add some more developer docs

---

cmd/nexctl/connectivity.go
cmd/nexctl/peers.go

typo: s/relay note/relay node/

---

pkg/oidcagent/handlers.go
ui/src/providers/AuthProvider.tsx

This should help users navigate to an org invitation from the  invitation email link.

frontend: redirect back to original window URL after login.

---

docs/development/code-organization.md

This documents the location of the major portions of the apiserver.

docs: Add apiserver to the code organization doc

---

Makefile

I had a problem where OLM was failing, so I checked and saw we're a
few versions behind. This updates to use the latest.

Use latest OLM - v0.27.0

---

internal/handlers/handlers.go
internal/handlers/invitations.go
internal/handlers/organization.go
internal/handlers/security_group.go
internal/handlers/vpc.go
internal/models/error.go
ui/src/pages/Invitations.tsx
ui/src/pages/UserOrganizations.tsx
ui/src/pages/Users.tsx

* reduce code duplication in handlers
* show roles in org member listing

fix frontend: invitation create org pick list was empty.

---

integration-tests/features/reg-key-api.feature
internal/handlers/reg_key.go

* allow org members to create RegKeys that uses resources in those orgs
* Added API tests for the above.

apiserver: fix reg-keys api to use new org ownership roles

---

cmd/nexctl/device.go

nexctl: add symmetric nat to full device list output

---

cmd/nexctl/device_metadata.go
internal/client/api_vpc.go
internal/client/custom_informer.go
internal/client/custom_service_network_sites.go
internal/client/custom_vpc_device_metadata.go
internal/client/custom_vpc_devices.go
internal/client/custom_vpc_security_group.go
internal/docs/docs.go
internal/docs/swagger.json
internal/docs/swagger.yaml
internal/handlers/device.go
internal/handlers/device_metadata.go
internal/handlers/events.go
internal/handlers/fetchmgr/memfm/mem_fetch_manager.go
internal/handlers/fetchmgr/redisfm/redis_fetch_manager.go
internal/handlers/fetchmgr/resource.go
internal/handlers/fetchmgr/tests/fetchmgr.go
internal/handlers/security_group.go
internal/handlers/service_network.go
internal/handlers/site.go
internal/handlers/vpc.go
internal/nexodus/join.go
internal/nexodus/nexodus.go
internal/util/json.go

An informer from nexd to access its data.
* Added the ability to create an informer for a Get operation
* Added a util.JsonStringer(x) that you can use for deferred json formatting.

apiserver/nexd: improve the meta data event apis so that we can use

---

Containerfile.playwright
ui/package-lock.json
ui/package.json

- debugging e2e failure with latest playwright version

Playwright bump
