nexodus-io/nexodus

- ui/src/pages/Zones.tsx
The Create Zone UI now has a boolean selector for setting the new zone as a Hub Zone.
> ui: Allow creation of hub zones

- ui/src/pages/Zones.tsx
Zones already have a friendly name, so drop the ID from the Zone list UI. The ID can still be viewed on the Zone detail view after a Zone is selected.
> ui: Drop ID from Zone list

- internal/apex/apex.go
- internal/client/device.go
- internal/handlers/device.go
- internal/models/device.go
- ui/src/pages/Devices.tsx
Have the apex client send the Hostname to the controller when creating a new Device.
In the UI, replace the Device ID with the Device's Hostname in the Device list. The ID is still visible in the Device details page.
> apex: Send controller the hostname for a device

- Containerfile.test
- integration-tests/integration_test.go
- integration-tests/util_test.go
- internal/client/user.go
- Changed Containerfile.test to run a shell to allow for stopping and restarting of Apex from IT.
- Enabled go-e2e to run in CI.
- Added restart and key deletion tests.
- Added create network in utils to prep for building out a NAT topology for testing symetric NAT.
> Make apex spawnable in IT containers

- internal/apex/configure-pull.go
- Relay nodes will discover endpoint ip:port pair from the endpoint dynamically when it connects. Otherwise, we have reflexive_ip:port collisions.
- TODO: we need symmetric NAT integration testing.
> Remove explicit endpoint addresses for relay nodes

- Makefile
While the docker-compose env is still around, this adds a target that's a shortcut for rebuilding the test environment - down/build/up.
> Makefile: Add recompose target

- .github/workflows/build.yml
- integration-tests/integration_test.go
- integration-tests/util_test.go
- Provisions a apex five-node deployment with seven containers total. The additional two containers are doing ip masquerading to setup a "easy" NAT scenario.
- This emulates the topology of two remote sites, both with firewalls facing the Internet with no inbress traffic allowed or any static NAT mappings from the outside to the inside interface of the NAT nodes.
- What is validated in the test is in order for spoke traffic traversal to occur between net1 and net2, spoke nodes are relayed through the relay node.
- Also validated is local address ICE pairing is reachable between nodes.
> Added e2e IT for NAT

- internal/apex/apex.go
- Changed to the new http://foo.bar controller URL
> Fix address discovery for darwin/windows

- ui/src/pages/Peers.tsx
The previous title for the Peer Show page was "Peer #<id>". The titles for all other pages was updated to a more friendly representation by changing the recordRepresentation on the Resource. I wasn't able to get that to work for peers.
Instead, this just explicitly updates the title for the page showing
details of a single peer. Now the title shows "Peer: Device <device>
to Zone <zone>."
There are no other places at the moment that would benefit from updating the recordRepresentation for peers, so this seems good enough.
> ui: Improve title to PeerShow page

- cmd/apex/main.go
- docs/design/design-discovery.md
- integration-tests/integration_test.go
- internal/apex/apex.go
- internal/apex/configure-hub.go
- internal/apex/configure-pull.go
- internal/apex/configure-utils.go
- internal/apex/discovery.go
- internal/apex/dump.go
- internal/apex/stun.go
- internal/apex/utils.go
- internal/client/peers.go
- internal/handlers/peer.go
- internal/models/peer.go
- Adds a keepalive managed by the agent and disables wireguard keepalives #170
- Now supports full mesh via reflexive addresses. State is pushed from the relay node since all nodes can establish a connection there and then reconciled by the agent depending on the agent environment. #113
- Discovers symmetric NAT and builds peers to only relay and local peers.
- The agent now manages what port wireguard will listen on to help with reflexive
NAT socket mapping and avoid overlap to be more compatible with more routers.
The exception is the hub-router/relay node that needs to have a well-known port
for all nodes to be able to dial into for state distribution until apex can
do NAT whole-punching independent of a relay node.
- Adds a `--relay-only` bool switch in the case of nodes that Apex is …
> Adds full mesh capabilities via reflexive addresses

- cmd/apex/main.go
- cmd/apiserver/main.go
- internal/apex/apex.go
- internal/apex/configure-hub.go
- internal/apex/configure-pull.go
- internal/apex/configure-utils.go
- internal/apex/keys.go
- internal/apex/utils.go
- internal/apex/utils_darwin.go
- internal/apex/utils_linux.go
- internal/apex/utils_windows.go
- internal/handlers/api.go
- internal/handlers/handlers_test.go
- internal/handlers/peer.go
- internal/handlers/zone.go
- internal/ipam/ipam.go
- internal/ipam/ipam_test.go
- internal/routers/middleware.go
- internal/routers/routers.go
- Doesn't pass cli.Context directly to the `apex` lib - argument parsing should be done in the main.go
- Makes a start on improving error handling in client code - don't Fatalf everywhere and prefer returning errors from functions.
Fixes: #171
> logging: Overhaul logging to use zap

- hack/kind/kind.sh
- integration-tests/integration_test.go
- integration-tests/util_test.go
- internal/handlers/peer.go
- e2e for child-prefix in a hub zone.
- fixed a bug where child-prefix was not updated in the peer table if the record already existed.
- added a gather function to make it easier to debug failed e2e test nodes.
- bumped kind.sh timers for the bandwidth challenged <sad_face>
> Adds child prefix hub zone e2e and bug fix

- Makefile
A recent change dropped the apiserver targets from the Makefile. The
'all' target still had an 'apiserver' dependency, but no 'apiserver'
target existed. We exclusively run the apiserver in a container, so we
don't need to build it directly here.
Re-add APISERVER_DEPS, as it's used as a dependency for the go-lint
target, and that still makes sense.
> Makefile: remove apiserver from all target

- Containerfile.ipam
- deploy/apex/base/ipam/deployment.yaml
grpc probes aren't available on the version of k8s in OpenShift
> deploy: Use exec probes for ipam

- deploy/apex/base/apiserver/postgres.yaml
- deploy/apex/base/ipam/postgres.yaml
The limitranges in our OperateFirst namespace are too greedy. Each container that doesn't specify a request/limit gets a limit of 500m CPU. Since the PGO requires 4 sidecars, that was 2 CPUs PER CLUSTER - and we have 2 of them. Effectively eating all of our resourcequota.
This commit adds smaller limits to the sidecars, so each postgres cluster will need 800m CPU - 300m CPU will be used for backup jobs. In effect, we'll need:
- Postgres x 2: 1600m
- Apex Services: 700m Total: 2100m
Leaving ample headroom even including 600m for backups.
> deploy: Fix postgres limits for the final time

- Makefile
- internal/apex/apex.go
- internal/apex/keys.go
- internal/apex/route.go
- internal/apex/stun.go
- internal/apex/utils.go
- internal/apex/utils_darwin.go
- internal/apex/utils_windows.go
- internal/apex/wg-deploy.go
- internal/apex/wg-iface.go
- internal/apex/wg-windows.go
- internal/apex/wg.go
- the windows wireguard utility requires a config file to bring up the wg interface. It is only there to bind the private key to the wg0 interface. This also used it to add ip to the iface. Peers are all managed with the same library across all platforms now.
- broke out interface operations into a seperate file.
> Add back windows support

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- Makefile
1. Build docker images for apiserver, frontend and in a seperate stage
2. Use the github actions cache to store image layers, hopefully speeding up image builds in future
3. Have the e2e job grab images from artifacts instead of building them and cache the `test` image layers
4. Have the e2e job call go test ./... directly instead of via the makefile in order to avoid calling other make targets
> ci: Speed up

- docs/README.md
- docs/scenarios/containers-on-nodes.md
Add a "Additional Feature" section to the docs, and document how the Apex agent can be instructed to act as a Subnet Router.
> docs: Document the use of --child-prefix

- internal/apex/apex.go
This function is only called when either stun was not requested or if stun failed. If it fails, it seems like we'd prefer to try to find an address this way than give up without an address.
> apex: Remove unnecessary stun option check

- Makefile
- cmd/apiserver/main.go
- deploy/apex/base/apiserver/deployment.yaml
- deploy/apex/overlays/dev/kustomization.yaml
- docs/README.md
- hack/kind/kind.sh
- internal/fflags/fflags.go
- internal/handlers/api.go
- internal/handlers/fflags.go
- internal/handlers/handlers_test.go
- internal/handlers/zone.go
- internal/handlers/zone_test.go
- internal/routers/routers.go
- ui/src/App.tsx
- ui/src/pages/Zones.tsx
This PR introduces the first phase of feature flags and uses a
feature flag to disable support for multiple zones (multi-zone).
The feature-flag backend is represented by the FFlags API, which, for 
now is just a simple backend with defaults that can be changed with
an environment variable. Eventually, we can replace this with one of
several other options that will allow us to do more advanced feature
controls.
Feature flags are exposed via our own API. They may be listed, or a
specific flag may be queried.
The UI consumes the API to know whether multiple zones are supported.
If they are not supported, the "Create Zone" button is disabled (or 
greyed out).
The Zone create/delete APIs also check the feature flags in the API 
server. These methods will be denied if the flag has multi-zone …
> Control multiple zone support with a feature flag

- Makefile
- docs/README.md
When running "make e2e", make sure that kind is installed and that the "apex-dev" kind cluster is running.
> Makefile: Check prereqs before running e2e tests

- hack/kind/kind.sh
This appears to break on Mac right now, so just block it until someone has a chance to figure it out.
> kind.sh: Only run on Linux

- hack/kind/kind.sh
Ensure mkcert is installed when running the cacert subcommand.
Emit a notice when the apex names have not yet been added to /etc/hosts.
> kind.sh: Add more environment checks

- integration-tests/integration_test.go
- internal/apex/apex.go
- internal/apex/route.go
- internal/apex/utils_darwin.go
- internal/apex/utils_linux.go
- internal/apex/utils_windows.go
- internal/apex/wg.go
- When a peer or device is deleted from the database, the cached peers are diffed against the latest peer listing. If the cache does not contain the peer, it is removed from all nodes in the mesh. Both the peer and routes are removed from the endpoints.
- This does not do anything on the device being deleted. That is still a tbd on how we handle that. The deleted node has no connectivity to the mesh/peers since it is removed from all of the tunnel endpoints unless it is added back to the mesh.
> Add peer deletes to the agent

- hack/apex-installer.sh
The apex agent installer script failed on an ubuntu 22.04 AMI on aws ec2. The issue was that the installer script was not able to install the wireguard package. The fix was to do an apt-get update prior to attempting the wireguard package install. This is generally a good thing to do in any case as well.
> Fix for "Installer fails on EC2 Ubuntu AMI"

- cmd/apiserver/main.go
- go.mod
- go.sum
- internal/database/database.go
- internal/database/migrations/20230113-0000.go
- internal/database/migrations/migrations.go
- internal/database/migrations/new.go
- internal/ipam/ipam.go
- internal/util/utils.go
This allows us to apply or rollback migrations.  This change also manually creates the unique indexes so that migrations work against cockroach.
> Use gomigrate to manage the DB migrations.

- internal/routers/middleware.go
- internal/routers/routers.go
- internal/util/with_trace.go
use traceID as the key to be consistent with what the ginzap middleware does.
Signed-off-by: Hiram Chirino <hiram@hiramchirino.com>
> fix: include the trace id in more of the logged messages.

- Makefile
A number of targets had docs with a single `#`, but the help text output generation looks for `##`.
> Makefile: Fix help text for some targets

- .github/workflows/deploy.yml
- .github/workflows/promote.yml
This should stop multiple concurrent merges racing to update the QA or Production images via kustomize
> ci: Add concurrency to deploy jobs

- internal/apex/apex.go
- internal/client/peers.go
- Prevents peer deletion if the peer lookup fails and throws an error instead of fataling out.
> Handle http errors in peer listings

- internal/handlers/peer.go
If a device joins as a normal device and after a disconnect it joins again as a hub-router, the peer list doesn't update the hub-router status in the GUI. Same happens if the device joins as a hub router and then as a normal device after disconnect.
Resolves #183 
> Properly update the hub-router status of the device

- .github/workflows/build.yml
Cancel the in-progress build job if new commit/force push done to same pr, avoid unnecessary queuing. 
> Cancel the in-progress build job on new commit/force push 

- internal/client/client.go
- To fetch the original token to refresh the token grant after the default 10hrs we need to enable the oidc offline_access option
> Add offline_access option for OIDC token refresh

- .github/workflows/build.yml
- Makefile
warning creeping in and showing up in the PRs
under "Unchanged files related warnings"
Also added make target yaml-lint so that dev's can run it locally before pushing the patch.
> Run yaml-lint with --strict to prevent yaml lint

- Containerfile.test
- Makefile
- hack/resolve-ip/main.go
Added info message when you start the test container so that beginners know what command they should run to get apexd up.
Added net-tools to the image incase you need to do some network troubleshooting. 
Fixed a Makefile message that referred to hack/kind/kind.sh
> fix: `make run-test-container` now works on osx

- cmd/apexd/main.go
- internal/apex/apex.go
- internal/util/go_with_wait_group.go
- internal/util/go_with_wait_group_test.go
- internal/util/run_periodically.go
Make the api a little more go idiomatic by using a Context cancellation to signal to *Apex that it should shut down and wait for the cancellation to occur using a WaitGroup.
Signed-off-by: Hiram Chirino <hiram@hiramchirino.com>
> chore: apexd should shut down cleaner on an os signal.

- .github/workflows/build.yml
- Makefile
- internal/apex/apex.go
- internal/apex/dump.go
- internal/apex/keepalive.go
- internal/apex/keys.go
- internal/apex/stun.go
- internal/apex/utils.go
- internal/apex/utils_linux.go
- internal/apex/wg-deploy.go
- internal/apex/wg-iface.go
- internal/apex/wg.go
- internal/ipam/ipam.go
In most cases, we should be using %w for errors in format strings. The exception is when calling log functions, as they don't support it.
For more info:
https://github.com/polyfloyd/go-errorlint
> lint: Add errorlint for go code

- integration-tests/util_test.go
This code assumed output was present in a certain format. If the interface exists, but has no IP address, this code will crash when trying to get a field out of empty output. This will catch it and return an error instead.
> test: Fix a panic in a test

- .github/workflows/build.yml
- .golangci.yaml
- Makefile
Use a config file instead of duplicating configuration between the Makefile and the github actions job.
Closes #415
> go-lint: Add a golangci-lint config file

- .github/workflows/build.yml
- .github/workflows/docs.yml
Move the markdownlint job out of the build workflow and into a new docs workflow. The build workflow does not run on a docs-only change. The new docs workflow will run on any change that includes a modification to a markdown file.
Closes #414
> actions: Create a docs workflow

- .github/workflows/build.yml
patterns in double quote vs single quote.
It's recommended to use single quote
https://docs.github.com/en/actions/learn-github-actions/expressions#literals
> Github actions has some weirdness around evaluating

- Makefile
- internal/apex/apex.go
- internal/apex/stun.go
- internal/apex/utils.go
- internal/apex/wg.go
Using a random high port for the wg is not guaranteed to not be in use by another process, so lets ask the OS for a dynamic port instead.
This now avoids an additional stun request once we have determined that the device is behind a symmetric nat.
Wait for apex to be deployed when running `make recreate-db`
> clean up: reduce code duplication in stun.go, use a dynamic port the wg interface that we can open.

- .github/workflows/build.yml
and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> fix a CI warning: The `set-output` command is deprecated 

- internal/apex/apex.go
- internal/apex/wg-peers.go
Update two spots joining an IP and port into a string to use the net.JoinHostPort() helper. This helper will ensure IPv6 addresses are handled properly. It doesn't matter now, but presumably it will eventually.
> apex: Use net.JoinHostPort()

- Makefile
- deploy/.crdSchemas/crdbcluster_v1alpha1.json
- deploy/apex/base/apiserver/deployment.yaml
- deploy/apex/base/apiserver/kustomization.yaml
- deploy/apex/base/ipam/deployment.yaml
- deploy/apex/base/ipam/kustomization.yaml
- deploy/apex/overlays/cockroach/cockroach.yaml
- deploy/apex/overlays/cockroach/kustomization.yaml
that changes the kind deployment to use cockroachdb.
The apiserver still needs some work to actually make it work.  But at least this gives developers a way to easily start testing against cockroach.
> chore: add a `make use-cockroach` task

- internal/apex/apex.go
- internal/apex/utils.go
- Prevent a user from providing an invalid prefix. For example a prefix of 172.16.100.5/24 will now be rejected and valid prefix 172.16.100.0/24 is suggested in the error message.
> Improve child-prefix network validation

- .github/workflows/build.yml
- .github/workflows/docs.yml
So that *.md only patches with any change in .vscode directory won't trigger build jobs.
> Add .vscode directory to paths-ignore for build and doc job

- Containerfile.ipam
We can back this out if I figure out how make the quay.io/apex/go-ipam image be multi-arch.
What docker file puts the /bin/grpc_health_probe binary into the [quay.io/apex/go-ipam:v1.11.3](http://quay.io/apex/go-ipam:v1.11.3) image?  I would have thought it was https://github.com/metal-stack/go-ipam/blob/v1.11.3/Dockerfile but that does not seem to do it.
> feat: build a multi-arch image for the ipam container.

- Containerfile.apex
Apex agent container image build is failing for windows platform, because the docker container 
file is using golang-1.19-alpine image to build the  binary, and obviously it's doesn't support windows/amd64-arm64
arch.
> Use golang-1.19 image, instead of golang-1.19-alpine

- .github/workflows/deploy.yml
You can't build windows containers from a linux worker
> ci: Don't build windows images

- Containerfile.apex
image to go-1.19 image to enable windows support.
That breaks the command to build the mkcert util
and this patch fixes it.
> Apex image build job moved from go-1.19-alpine

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- .gitignore
- Containerfile.mock
- Makefile
- contrib/rpm/apex.service
- contrib/rpm/apex.spec.in
- docs/README.md
```
commit 2d944741186134f7b77be3eebecab4f30804df37
Date:   Mon Feb 20 20:49:36 2023 -0500
rpm: Package the manpages
commit 629050c550e1809b8df20cfcf3ec678e4d88d69a
Date:   Mon Feb 20 18:02:41 2023 -0500
Makefile: Add manpage generation
commit cf644df5a14467d920128948c1274803e29c6964
Date:   Mon Feb 20 17:11:44 2023 -0500
docs: Document how to use the copr repo for rpms
commit 33e8f3dbf5b1f9b78a1f765e0f59575565ff2faf
Date:   Mon Feb 20 14:20:33 2023 -0500
ci: …
```
> Publish RPMs to a public repo after commits to main

- .dockerignore
- .github/workflows/build.yml
- Containerfile.test
- Makefile
- deploy/apex/overlays/cockroach/kustomization.yaml
This also pegs the build to a specific revision of crunchy db and makes the test container multi-arch.
> Faster make deploy and recreate db

- docs/README.md
- integration-tests/integration_test.go
- internal/apex/apex.go
- internal/handlers/organization.go
- Updated addressing in docs and removed some zone mentions as well. This is not intended to fix all of the zone removal docs. Once we have org user moves we can add back those intructions.
> Change the default org prefix to CGNAT

- .github/workflows/deploy.yml
The deploy workflow fails often if additional PRs have been merged by the time this job runs. This change will check to see if there are any commits in main that are not in the branch the job is running on. If so, it will not attempt to push a commit that would fail.
> deploy: Check for new commits to main

- Makefile
- cmd/apexctl/local.go
- cmd/apexctl/main.go
- cmd/apexd/main.go
- integration-tests/util_test.go
- internal/apex/apex.go
- internal/apex/ctlserver.go
- internal/client/auth.go
- internal/client/client.go
Add a unix socket control interface on linux. This interface uses
jsonrpc and supports checking the status apexd. It will report back
the info needed to register the device if it's waiting for auth. This
would be one way to get info when running apex as a daemon. The other
would be from the daemon logs.
apexctl now knows how to retrieve this status information by running:
apexctl apexd status
We now embed a version at build time into each binary. This is done
using ldflags to set the value of main.Version.
apexctl can report its own version.
apexctl version
apexctl can also report the version of a running apexd.
apexctl apexd version
When running subcommands of "apexctl apexd" other than "version",
apexctl will first validate that the apexctl and apexd versions match.
Signed-off-by: …
> apex: Add unix socket control interface

- docs/governance/pull-requests.md
Start a doc where we can document our guidelines for handling pull requests. This will help ensure a shared understanding of what we expect from each other as project committers.
> docs: Add a doc on pull request process

- .github/workflows/docs.yml
- Makefile
- docs/README.md
The default config of this job only checked the root directory, so everything in docs/ was not checked in CI.
Fix some md-lint issues in docs/README.md.
Shorten the Makefile target name to md-lint.
> lint: Make md-lint check the whole project

- .github/workflows/qa-ec2.yml
- ops/ansible/aws/ansible.cfg
- ops/ansible/aws/create-zone/tasks/main.yml
- ops/ansible/aws/deploy-ec2.yml
- ops/ansible/aws/deploy-mesh/tasks/main.yml
- ops/ansible/aws/rootCA.pem
- ops/ansible/aws/terminate-ec2/tasks/main.yml
- ops/ansible/aws/validate-connectivity/tasks/main.yml
- ops/ansible/aws/vars.yml
- Adds vars to repo secrets.
- Ansible vars are encrypted and stored in GH secrets. These vars contain the deployment details (node count, VPCs, etc)
- Once nodes are deployed, connectivity is verified from the relay node to all of the spoke nodes. Output is saved and displayed in the action output. This will be tweeked and further tests will be added once this is up and functional via webhooks from operate first.
> Adds QA e2e in ec2 for operate first QA deployment

- README.md
Elsewhere in our docs we talk about Edge. This is the only spot we used "IoT". Change it to be more consistent.
> README.md: Use Edge instead of IoT

- docs/deployment.md
- docs/design/database.md
- docs/observability.md
- docs/scenarios/kubernetes-edge.md
Update to reflect the changes inside of deploy/. In passing, also drop some references to running on operate-first, as we are no longer using that infrastructure.
> docs: Complete removal of apex from docs

- .github/workflows/qa-ec2.yml
- ops/ansible/aws/deploy-ec2.yml
- ops/ansible/aws/recreate-api-db.yml
- This allows for dispatching of ec2-qa without any manual interaction with the api-server. After the job completes the stack is reset for the next dispatch.
> Reset the nexodus stack after ec2 qa runs

- docs/security.md
The nexodus repo is configered to allow private reporting of security issues. Update the security document to refer to this feature as our process for taking vulnerability reports.
> docs: Document vulnerability reporting process

- ops/ansible/aws/deploy-ec2.yml
- ops/ansible/aws/deploy-mesh/tasks/main.yml
- ops/ansible/aws/inventory.txt
- ops/ansible/aws/setup-ec2/tasks/main.yml
- ops/ansible/aws/validate-connectivity/tasks/main.yml
- ops/ansible/aws/vars.yml
- This adds relay testing for qa dispatch. It is a much more in depth infra and validation than what can be mocked up in CI for relay testing.
- This is dispatched from GH actions. Previous tests prior to this can be viewed in actions history, this adds additional nodes joined as --relay-only.
> Adds ec2 e2e for relay nodes

- internal/nexodus/ctlserver.go
- internal/nexodus/wg-peers.go
- Suppressing some informational logging to make it a bit less noisy for the user. Currently displaying the user's wg address and peer addresses is plenty to get a bit of dopamine and verify connectivity.
> Change some agent side informational logging to debug

- Makefile
before restarting the depending pods.  It was not reliable.
> fix: #533 remove attempt to wait for the DB to be up

- .github/workflows/promote.yml
the QA deployment and it is deployed successfully. Promote job will use the same image tags that is deployed by deploy job in QA deployment, so dependency on
build-images is not required
> Promote job will run once deploy job triggers

- cmd/nexd/main.go
Lack of the URL is not an error serious enough to dump a stack trace in the logs. Just dump an info message before exiting cleanly.
> nexd: Don't dump a stacktrace if no url is provided

- internal/nexodus/wg-peers.go
- Commit prevents the relay node from adding a /32 entry since the relay node needs the full org prefix in the peer e.g. /16
- It is getting the /16 but throwing an error when it tries to add another further down in the method.
> Skip adding the relay node as a /32 peer

- cmd/nexd/main.go
In general, stack traces are not useful to users running nexd. Disable them in production mode. They will still be there when being run in debug mode.
> nexd: Stop including stack traces in logs

- .github/workflows/build.yml
- Makefile
Add pretty output for running `make gen-docs`. Full output from the tool can be seen when you run with `NOISY_BUILD=y` like this:
$ NOISY_BUILD=y make gen-docs
Also make some other jobs depend on the gen-docs job. It runs in 20% of the time of go-lint, so make jobs that depend on go-lint depend on this one too. If the docs are broken, don't waste time running all the more consuming jobs.
> gen-docs: Add job pre-reqs and pretty Makefile output

- .gitignore
- integration-tests/integration_test.go
- integration-tests/util_test.go
- internal/nexodus/keys.go
- internal/nexodus/utils.go
- Commit creates a file with the nexd run options for each node, copies them to the node for execution and pipes logs to a file. The file is then picked up in gather for a dump in the case of a test failure for easier debugging.
> Add nexd logging to e2e

- cmd/apiserver/main.go
- cmd/nexctl/main.go
- cmd/nexd/main.go
- internal/client/auth.go
- internal/client/client.go
- internal/client/options.go
- internal/nexodus/nexodus.go
add --insecure-skip-tls-verify flag to the nexd cli tool.  This can be handy if your testing against a nexodus server that is using self signed certs and your device has not installed those certs into the system certs.
chore: Uppercase first letter of all flag Usage to be consistent with how other tools like git and kubectl show help.
> feat: add --insecure-skip-tls-verify flag to the nexd cli tool

- integration-tests/integration_test.go
- integration-tests/util_test.go
- Now that we launch from a file for easier log piping we can remove the groutines.
- Fixed a teardown issue of a container in the TestRelay test.
- Bumped context timers for tshooting parallel tests.
> Remove go routines from nexd launch in e2e

- cmd/nexctl/device.go
- internal/nexodus/nexodus.go
- ui/src/pages/Devices.tsx
- This adds a check prior to a node joining an organization as a relay node to verify there isn't an existing one already in the database. If there is an existing relay, the agent exits with instructions to delete the device ID in order to join as a relay for the organization. Currently if two nodes join as a relay it is not handled and becomes a free for all as to which relay a node will add a tunnel with the org prefix.
- Also adds a device relay field to nexctl and the UI.
> Add a check for existing relay in the nexd agent

- mkdocs.yml
- netlify.toml
Enable a bunch of features of mkdocs-material. Document most of the config so it's easy to tell what each option is doing. Also fix the github doc edit path.
> docs: Adjust docs site theme configuration

- internal/nexodus/wg-peers.go
- Resolves #606 by applying the same relay check logic that currently exists for reflexive address peering to local address peering.
> Add a check for a relay node in peer setup for local peering

- cmd/nexctl/main.go
- cmd/nexctl/user.go
- internal/client/user.go
- internal/database/database.go
- internal/database/migration_20230314_0000/20230314-0000.go
- internal/docs/docs.go
- internal/docs/swagger.json
- internal/docs/swagger.yaml
- internal/handlers/device.go
- internal/handlers/handlers_test.go
- internal/handlers/organization.go
- internal/handlers/user.go
- internal/models/organization.go
- internal/models/user.go
- internal/routers/routers.go
- Adds an endopint to remove a user from an organization and the associated nexctl cli operations. See comments for sample output.
- Changes the name of the db table user_organization to user_organizations to adhere to gorm's pluralizing of structs to snake_case for operations on that table.
- Enables orgDeletes and userDeletes by adding the clause.Associations deletes that remove the associations in user_organizations.
> Add endpoint delete for user removal from an org #439

- cmd/nexctl/main.go
- internal/client/client.go
also associate the configured http client earlier in the client login flow os that the insecure client is used access the oidc server.
> feat: add --insecure-skip-tls-verify option to the nexctl cli tool.

- cmd/nexd/main.go
The help text previously said:
nexd [global options] command [command options] [arguments...]
Now it says:
nexd [global options] command [command options] controller-url
> nexd: Update help text to include controller-url

- cmd/nexd/main.go
Rename this env var to use a NEXD_ prefix like all other env vars.
> nexd: Rename env var with APEX_ prefix

- Makefile
This isn't needed since golangci-lint already runs this by default.
You can check which linters are used if you run the tool manually with the verbose flag, `-v`.
```
$ golangci-lint run -v ./...
...
INFO [lintersdb] Active 9 linters: [errcheck errorlint gosec gosimple govet ineffassign staticcheck typecheck unused]
...
```
> Makefile: drop go vet

- integration-tests/feature-flags-api.feature
Seems we send slightly different 401 responses.  We should likely give 401’s a json body to be more consistent with other errors our API has.
> Fix: the latest envoy change breaks the cucumber test.

- internal/nexodus/stun.go
- internal/nexodus/utils.go
Fix stun requests to ensure they are always IPv4 and fix one only spot that assumed IPv4 but didn't force it.
```
commit ee2fa95a4a499831544f97be79d060a9d4e58df3 (HEAD -> v6fixes)
Date:   Fri Mar 24 14:19:00 2023 -0400
utils: Ensure discoverGenericIPv4 is actually IPv4
Force this method to use IPv4 since that is the intent.
In passing, using the net.SplitHostPort() method instead of manually
splitting the string, as this is best practice to avoid accidental
parsing mistakes (primarily with IPv6, but we should use the helper
everywhere).
commit 5f18f43b2dae76a1ec98b14465b64c4416d36c25
Date:   Fri Mar 24 14:13:28 2023 -0400
stun: Ensure we issue stun …
```
> Ensure stun requests are IPv4

- Makefile
Add NEXODUS_GCFLAGS to allow setting flags to be passed to `go tool compile`. No flags are specified here by default. They can be set when running `make` like this:
```
$ NEXODUS_GCFLAGS="-cpuprofile foo" make dist/nexd
```
> Makefile: Add NEXODUS_GCFLAGS

- docs/development/design/project-name.md
Standardize on how we refer to a network managed by Nexodus in documentation. Earlier in the project we referred to this as a "zone," but that construct is gone for now. At some point a network slicing construct may be reintroduced within organizations, but for now just use the more generic "network" terminology.
> design: Add Nexodus network to our project terminology

- .github/workflows/qa-ec2.yml
- On dispatch, provide the sizing options  small | medium | large to adjust the node counts of the deployments sized in the ansible var files stored in GH secrets.
> Add sizing options to EC2 QA deployment

- internal/nexodus/keys.go
Reduces our dependency on the wg binary.
> perf: use the wgctrl go module to generate the pub/private key pairs

- cmd/nexctl/invitation.go
- cmd/nexctl/main.go
- docs/development/design/database.md
- integration-tests/device-api.feature
- integration-tests/util_test.go
- internal/client/invitation.go
- internal/database/database.go
- internal/database/migration_20230327_0000/20230217-0000.go
- internal/docs/docs.go
- internal/docs/swagger.json
- internal/docs/swagger.yaml
- internal/handlers/device.go
- internal/handlers/handlers_test.go
- internal/handlers/invitations.go
- internal/handlers/invitations_test.go
- internal/handlers/organization.go
- internal/handlers/organization_test.go
- internal/models/device.go
- internal/models/error.go
- internal/models/invitation.go
- internal/models/organization.go
- internal/models/user.go
- internal/routers/routers.go
This provides API endpoints that allow users to be invited into organizations. Support for this is gated behind the multi-organization feature. Client code has not been updated to deal with cases where a user is in > 1 organization.
> Support User/Org Invitations

- docs/development/design/userspace-mode.md
This document includes a proposal for adding a new proxy mode to `nexd` that allows interfacing with a Nexodus network with a userspace-only approach. This allows connectivity in environments where privileges to create new network interfaces are not available.
Issue #187
> design: Propose a userspace-only mode for nexd

- integration-tests/integration_test.go
- integration-tests/util_test.go
- This was a residual bug from zone removal where CIDRs collapsed into prefix that overlapped between orgs.
- Instead of TunnelIP we now use the CID for deletions resolving the bug that prevented concurrent testing.
- Also removed the Cleanup() as I think that was an issue as well. The containers get torn down regardless when the parent context exits. I've noticed a flake in GH with Cleanup that had to have been from a premature teardown. Either way, removing them doesn't add overhead since it's all concurrent anyways.
> Resolve the bug blocking suite.T().Parallel() on all tests in e2e

- internal/nexodus/dump.go
- internal/util/utils.go
Reduces our dependency on the wg binary.
> perf: use the wgctrl go module to dump the wg sessions.

- cmd/nexctl/local.go
- cmd/nexctl/main.go
- cmd/nexd/main.go
- internal/nexodus/ctlstatus.go
- Add a check to prevent more than one nexd being initialized
- Added checks for OS on nexctl for unsupported OSs
> Add a nexd socket check for an existing process running

- docs/user-guide/agent.md
- docs/user-guide/discovery-and-relay.md
- docs/user-guide/nexctl.md
- docs/user-guide/subnet-routers.md
The `user-guide.md` file has become a bit large. It's already under its own sub-folder in the docs, `user-guide`. Split it apart into more focused topics as a more scalable way to organize this information as we continue to grow.
In this change, we now have separate files for these topics which were previously combined in `user-guide.md`.
- The nexd agent
- Discovery and Relay modes
- nexctl
- Subnet Routers
> docs: Split up the user guide

- internal/routers/middleware.go
- internal/util/cache/memoize.go
- internal/util/cache/memoize_test.go
We now fetch the jwk’s and the first API request, and retry again very 5 seconds if the fetch fails.
> fix: nexodus would fail on startup if it could not fetch the jwks certs

- cmd/nexd/main.go
- go.mod
- go.sum
- internal/nexodus/keys_linux.go
- internal/nexodus/keys_windows.go
- internal/nexodus/nexodus.go
- internal/nexodus/nexodus_linux.go
- internal/nexodus/nexodus_userspace.go
- internal/nexodus/wg-deploy.go
- internal/nexodus/wg-iface.go
- internal/nexodus/wg.go
This is the next step for userspace-only mode support after PR #685.
This commit introduces the core networking and wireguard code for the 
userspace-only mode of operation. There is no real user-visible
behavior introduced yet. It is not exposed via `nexd` yet, but you can 
test out the core functionality with an env var.
You can observe with the following invocation of `nexd`. Note that
`root` or `sudo` are not required here. It is intended to be used
without any elevated permissions.
```
NEXD_LOGLEVEL=debug NEXD_USERSPACE_MODE_TEST=true dist/nexd --username kitteh1 --password floofykittens https://try.nexodus.local
```
If you watch the output, you'll see the userspace stack get 
initiatlized. All of the same discovery and peering that `nexd`
normally does will occur. One exception is …
> nexd: Add core handling for userspace mode

- .markdownlint-cli2.yaml
- cmd/nexd/main.go
- docs/user-guide/nexd-proxy.md
- internal/nexodus/nexodus.go
- internal/nexodus/userspace_proxy.go
- mkdocs.yml
This commit makes use of the ability to run entirely in userspace mode to implement basic L4 proxy functionality that requires no elevated privileges.
This mode can be used in a Kubernetes Pod where `nexd` is not able to create a new network device. It's possible to grant a pod the access it needs, but in many cases an application developer does not have this level of access available.
Multiple ingress or egress proxy rules may be specified at the same time, but they all must be specified as command line arguments. Runtime management of rules will come later.
Documentation on how to use this mode can be found in `docs/user-guide/nexd-proxy.md`. A preview of these docs can be found here: https://deploy-preview-700--nexodus-docs.netlify.app/user-guide/nexd-proxy/
Closes #187
> nexd: Add an L4 proxy mode

- .github/workflows/build.yml
- .gitignore
- Makefile
Prior to this change, every time you ran `make go-lint`, another lint target, or a target that depends on one or more linters like running `make all`, the linters would run every time.
This change makes the lint tools only run if the code they lint has changed since the last time they ran. It does so by tracking the time it last changed as a `touch`ed file and allowing `make` to determine whether any source files are newer.
There's a bit of new filtering going on to make sure that only the appropriate files are considered dependencies. For example, nexd and nexctl do not need to be rebuilt in the the api docs are regenerated, as those are only built with the apiserver.
The `go-lint-prereqs` target was moved to an "order-only prerequisite". This tells `make` that it should be run prior to …
> Makefile: Only re-run linters if necessary

- .markdownlint-cli2.yaml
- docs/user-guide/nexd-proxy.md
This section of the docs demonstrates how to run two docker containers with a nexd proxy in each one. These instructions just wroked for me against our prod deployment while tethered to a mobile network.
> docs: Write up an end-to-end demo of nexd proxy

- integration-tests/util_test.go
- There isn't any output from the containerexec method so if there is a failure you simply get nil from err and a blank from output since that is a script getting piped to logs. The gather method collects logs for output and debugging. This changes it to just require the script is executed via containerexec.
- Also Im seeing a false positive on a test sourcing from this.
> Remove the suite.fail from renNexd() in e2e

- cmd/nexd/main.go
Exit with an error if nexd is started with a top-level flag that is incompatible with `nexd proxy`.
> nexd: Error on flags incompatible with proxy

- cmd/nexctl/user.go
- integration-tests/device-api.feature
- integration-tests/integration_test.go
- integration-tests/invitation-api.feature
- integration-tests/organization-api.feature
- integration-tests/organizations-devices-api.feature
- integration-tests/organizations-users-api.feature
- integration-tests/steps_test.go
- integration-tests/users-api.feature
- internal/client/organization.go
- internal/cucumber/cucumber.go
- internal/cucumber/http_response.go
- internal/docs/docs.go
- internal/docs/swagger.json
- internal/docs/swagger.yaml
- internal/handlers/device.go
- internal/handlers/handlers.go
- internal/handlers/organization.go
- internal/handlers/organization_test.go
- internal/handlers/user.go
- internal/handlers/user_test.go
- internal/models/organization.go
- internal/models/user.go
- internal/nexodus/nexodus.go
This adds more cucumber tests and it also 'flattens' the api responses.  Getting resource no longer joins the associated resources in the response.  This will allow us to have a more consistent data access cost per API request and make rate limiting work better.  This also simplifies the overall API.
> Flatten API responses and add more tests

- .gitignore
- Makefile
Don't run the `generate` target if no dependent code has changed since the last time it ran.
> Makefile: Fix generate to only run if necessary

- Makefile
- docs/development/integration-tests.md
To run a specific test, use the NEX_TEST variable:
```
NEX_TEST=TestNexodusIntegrationSuite/TestProxyEgress make e2e
```
> Makefile: Allow running a specific e2e test

- integration-tests/util_test.go
A log messsage about running a command in a container was misplaced. In an error case, it wouldn't be shown at all. In all cases, it didn't show up until after the command was already executed. This can be confusing when watching test execution.
> e2e: Log container exec before, not after the exec

- integration-tests/integration_test.go
- integration-tests/util_test.go
Make the handling of the v6 arg more explicit by making it a named type with two constants that represent possible values. It is also now a boolean instead of an int, since it was really a boolean in practice.
Make a similar change for how IP family is passed around as a string. There were only 2 valid values, so make it a set of typed constants.
> e2e: Use types for sets of constants

- .gitignore
- Makefile
This speeds up the integration test development working when running `make e2e` a bunch. This way you don't have to wait for `docker build` x3 to finish every time.
> Makefile: Only rebuild test-images if necessary

- nexrc.env
I didn't want to type `try.nexodus.127.0.0.1.nip.io` all the time, so I made this to keep in my environment. I figured others may want the same so I put it in the repo.
> Add nexrc.env for easy sourcing of nexodus URLs

- Containerfile.test
- integration-tests/integration_test.go
Add a test for `nexd proxy` ingress and egress rules. Both tests have two nodes, one running normal nexd and the other running nexd proxy. One side has an http server and the other runs curl. The roles switch based on which scenario is under test.
I added python3 and curl to the ubuntu test container for this scenario.
There's one hack in a test with a TODO comment to improve. It makes an assumption that our ipam is handing out IPs sequentially. We can't get the IP like we do normally because we can't read wg0 from the container since there's no interface. We could either add a new `nexctl nexd` command to get wireguard state, or we could query the nexodus service for the required device info. The hack at least works for now.
Closes #701
> e2e: Add nexd proxy e2e tests

- internal/nexodus/nexodus.go
- internal/nexodus/utils.go
- internal/nexodus/wg-peers.go
- Adds the entire STUN binding to the device registration as oppposed to just the IP addr. Also adds netip.AddrPort typing to the ax receiver.
> Register nodes with reflexive addr:port binding

- internal/client/apiclient.go
- In the scenario where an agent's reflexive address changes, the time to re-establish polling for a Linux stack was 15m+ while OSX was 1-2m. Both unacceptably long. This gets them both down to < 1second.
Quick summary of each field:
- DialContext: This field specifies a function that establishes a network connection to a remote server. In this case, it uses a custom net.Dialer with a 30-second timeout and keep-alive interval.
- TLSHandshakeTimeout: This field specifies the maximum amount of time that the transport will wait for a TLS handshake to complete when establishing a secure connection.
- ResponseHeaderTimeout: This field specifies the maximum amount of time that the transport will wait for the response headers to be returned after sending a request.
- ExpectContinueTimeout: This …
> Resolve long timeouts in the case of an agent NAT binding change

- internal/nexodus/nexodus_darwin.go
- Userspace wg was using a random port. Still worked in most scenarios since local peering was likely able to be initiated in the other direction.
> bugfix: explicitly set the darwin listen port

- .github/workflows/build.yml
- .gitignore
- Makefile
Move all of the files used to track when a target last ran into dist/. This makes it so we don't have to update the `clean` target and `.gitignore` file for each new dotfile added.
> Makefile: Move target timestamp tracking to dist/

- integration-tests/integration_test.go
- integration-tests/util_test.go
Prior to this commit, there were 3 scenarios:
- single ingress rule
- single egress rule
- 1 ingress rule + 1 egress rule
This commit adds the following to ensure that multiple rules of the same type also work as expected.
- multiple ingress rules
- multiple egress rules
A second commit in this PR changes how testcontainer names are generated so that the test name piece is automatic. This was inspired by having multiple copy/paste errors with the calls to createNode().
> e2e: Add two additional proxy test scenarios

- integration-tests/integration_test.go
- integration-tests/util_test.go
- internal/nexodus/nexodus.go
- internal/nexodus/wg-iface.go
- internal/nexodus/wg-peers.go
- For container scenarios, check if v4/v6 forwarding is enabled in the proc fs before trying to set it. Setting it will fail in a container and an error will be returned. But when spawned with: --sysctl net.ipv4.ip_forward=1 --sysctl net.ipv6.conf.all.forwarding=1 nexd will pass the settings check and not try and modify the kernel setting.
- Added v6 fwding to the v6 disabled test container, both can be true at the same time (ipv6 disabled with ipv6 fwding enabled).
- Removed relay from the v6 disabled test to keep a v6 disabled container profile.
> Add additional checks for relay nodes

- Makefile
- pkg/oidcagent/.github/workflows/ci.yml
I got a failure on `make -j all` that shows a dependency issue where the linters ran before the api client code was in place:
```
WARN [runner] Can't run linter goanalysis_metalinter: buildir: failed to load package : could not load export data: no export data for "github.com/nexodus-io/nexodus/internal/api/public"
ERRO Running error: 1 error occurred:
* can't run linter goanalysis_metalinter: buildir: failed to load package : could not load export data: no export data for "github.com/nexodus-io/nexodus/internal/api/public"
```
> Makefile: Run gen-openapi-client before linters

- cmd/nexd/flags_unix.go
- cmd/nexd/flags_windows.go
- cmd/nexd/main.go
- internal/client/apiclient.go
Having this feature on provides a better user experience. The option is still present if another directory is desired. The default for linux and mac is a pretty standard location for this type of thing: /var/lib/nexd/. The default for windows is the same directory we're using for other nexd things on Windows (C:/nexd).
> nexd: Set state-dir by default

- .github/workflows/build.yml
This ensures custom build flags in the Makefile are not omitted when builds are done in CI. I noticed after installing a binary from s3, the version was not set in the binary. This should fix it.
> ci: use makefile for binary builds

- cmd/nexctl/device.go
- integration-tests/device-api.feature
- integration-tests/integration_test.go
- internal/api/public/model_models_add_device.go
- internal/api/public/model_models_device.go
- internal/database/database.go
- internal/database/migration_20230403_0000/20230403-0000.go
- internal/docs/docs.go
- internal/docs/swagger.json
- internal/docs/swagger.yaml
- internal/handlers/device.go
- internal/models/device.go
- internal/nexodus/nexodus.go
- internal/nexodus/nexodus_darwin.go
- internal/nexodus/stun_darwin.go
- internal/nexodus/stun_linux.go
- internal/nexodus/stun_windows.go
- internal/nexodus/utils.go
- internal/nexodus/utils_darwin.go
- internal/nexodus/utils_linux.go
- internal/nexodus/utils_windows.go
- internal/nexodus/wg-peers.go
- Use bpf to send STUN requests sourced from the bound wg listener for Liinux.
- Use `SO_REUSEPORT` for wg userspace for Darwin.
- When a NAT binding change is detected via STUN requests, the node updates all peers without the need of a discovery node to distribute the state. This is currently for Linux for OSX nodes. Windows is a followup.
- #742
> Discovery without a designated disco node

- contrib/nexodus-installer.sh
* curl was set to run silently. If the download takes a while, it's not clear what's happening while the install script hangs. This gives more clear visual indication of what the script is doing.
* Download the correct binary for apple silicon macs.
* Add a verbose (-v) option so you can see each command as it is executed
* Fix download URLs to be correct for getting current binaries
> installer: Resolve a few issues

- cmd/nexctl/connectivity.go
- cmd/nexctl/main.go
- docs/development/design/nexodus-connectivity.md
- go.mod
- go.sum
- internal/nexodus/ctlconnectivty.go
- internal/nexodus/keepalive.go
- internal/nexodus/nexodus.go
- internal/nexodus/wg.go
- Let wireguard manage keepalives. Set to a generally accepted best interval timer of 20s which is plenty to keep NAT bindings open on firewall/middleboxes. It is also one less thread nexd is maintaining. Would also make sense to catch any issues with it now rather than later. If it generates too much traffic in scale testing we can look to optimize as needed. Also it is more rigorously vetted in the wild with peer counts in the hundreds and beyond.
- Use the keepalive functions for a ctl function to probe for peer connectivity that the user can run. The function is batched so as not to fire off hundreds of simultaneous probes and to give priority to wg keepalives.
> Replace custom keepalives with wg built-in persistant keepalive

- .github/workflows/qa-ec2.yml
Corresponds to: https://github.com/redhat-et/rosa-apps/pull/57
addresses: https://github.com/nexodus-io/nexodus/issues/548
This should enable the workflow to be triggered from a webhook on the nexodus side.
> modify the qa-ec2 workflow for triggering via argcod notifications webhook

- Containerfile.mock
- Containerfile.nexd
- Containerfile.test
The `test` and `nexd` images were built on `fedora:36`, but `37` is the latest GA version. The `latest` tag always points to the latest GA, so just use that.
The mock container used `38`, but `latest` is a better choice and should work just fine.
> Build images with latest GA fedora

- .github/workflows/dev-ec2.yml
May be possible to pass a size parameter via argo but keeping it simple to start with for the initial testing with a single set of ansible variables.
> Break out the ec2 dev and size tests from the argo workflow

- .github/workflows/dev-ec2.yml
- Enables both api-server and agent in ec2 instead of just the agent.
- You can choose either a branch or PR to deploy to ec2. Before it was just main.
> Adds api-server support testing for ec2-e2e

- .github/workflows/build.yml
- Makefile
While moving from test image to nexd image,
dist/nexd and dist/nexctl pre-req targets were
not added back. These binaries are needed to run
the local e2e.
In Github CI job e2e was working because the job explictly build these binaries.
This patch adds the dist/nexd and dist/nexctl targets to e2e dependency, and removes the explict building of these binary in the build job, as it's not needed anymore.
> Fix local e2e test

- .github/workflows/build.yml
because it doesn't use make targets for running
integration test, it invokes directly.
> We do need to build binaries in build job

- cmd/nexd/main.go
I reviewed commit 96a25df2ce3629906b66a3798c1fb549e2c824fb post-merge. This includes a couple of tweaks I wanted to make.
1. Use the pre-existing Linux constant in the nexodus package instead of defining a new one.
2. Use "Nexodus Service Options" instead of "ApiServer Options" to be more consistent with the naming conventions documented in `docs/development/design/project-name.md`.
> nexd: tweaks to agent refactor

- internal/nexodus/nexodus.go
This is just a minor simplification that I noticed while reviewing a PR that changed code nearby.
> nexd: Simplify checkUnsupportedConfigs()

- Containerfile.nexd
- docs/user-guide/nexd-proxy.md
- go.mod
- hack/udping/udping.go
- hack/udpong/udpong.go
- integration-tests/proxy_test.go
- internal/nexodus/userspace_proxy.go
commit 431a691824d38f34b41a4ccd8e78cc17323f1b06
Date:   Thu Apr 13 13:48:50 2023 -0400
nexd: Add more debug tools to container
Add `nc` and a couple of custom UDP utilities to do the most trivial
of UDP testing.
commit 2a57dc0155100e174e39ee043d1d8076b0b5c3a0
Date:   Fri Apr 7 09:35:15 2023 -0400
nexd: Add udp egress proxy support
This commit introduces UDP egress proxy support. I will add ingress
support in a follow-up change.
UDP proxy support is a bit more complicated than TCP support. We need
to allow return traffic back to each originating client, so we have to
do our own primitive connection tracking from within the proxy. These
flows time …
> nexd: Add egress UDP proxy support

- docs/index.md
Change "IP connectivity" to just "connectivity" since proxy mode allows more than just IP-level connectivity.
Add "L4 Proxy" as a line item on our home page to call out that while it's an L3 solution, there is also an L4 mode for non-privileged environments.
> docs: Add proxy mode to docs home page

- .github/workflows/dev-ec2.yml
- hack/e2e-scripts/aws-e2e-pr-gather.yml
- ops/ansible/aws/deploy-mesh/tasks/main.yml
- ops/ansible/aws/deploy-relay/tasks/main.yml
This will improve debugging of `dev-ec2` workflows since agent nodes are ephemeral and the api-server may get queued directly into another workflow run.
> Fetch nexd and api-server logs and upload as artifacts in dev-ec2 workflow

- internal/nexodus/nexodus.go
- An invalid controller URL will almost always hit the https check rather than the `url.Parse`. Virtually anything passes that check.
- Log what the user passed in case they typo subcommands that don't contain `--foo`, e.g. router|proxy|relay
> Add more checks and messaging to the user for invalid urls

- cmd/nexctl/local_unix.go
- integration-tests/helper_test.go
- integration-tests/proxy_test.go
- integration-tests/util_test.go
- internal/nexodus/ctlserver.go
- internal/nexodus/ctlserver_unix.go
- internal/nexodus/nexodus.go
commit 0b63c243eb162eaadd1e86dbd2dcb6f2db47b0b5
Date:   Fri Apr 14 20:25:49 2023 -0400
nexctl: Add ability to get tunnel IPs from nexd
Add a new command to `nexctl` to get the IPv4 or IPv6 tunnel addresses:
* `nexctl nexd get tunnelip`
* `nexctl nexd get tunnelip --ipv6`
commit 1a5bd72d2d8d554b24b7a213a11adf54d3f2938d
Date:   Fri Apr 14 21:07:09 2023 -0400
nexd: Open a unix socket in proxy mode
Turn on the unix socket interface for proxy mode. Instead of using
`/run/nexd.sock`, it defaults to `nexd.sock`. This is a safer default
as a place we can write to. The primary use case for this mode is a
container, so it seems fine to me.
Update `nexctl` to …
> nexctl: Add ability to get tunnel IP from nexd

- internal/handlers/handlers_test.go
- internal/ipam/ipam_test.go
- internal/ipam/test_ipam_server.go
These two suites both opened an ipam listener on the same TCP port, which I saw causing failures in CI.
> test: Fix tcp listener port conflict

- Makefile
I got the following error on a build:
```
$ make -j all
[OPENAPI CLIENT GEN] internal/docs/swagger.yaml
make: *** No rule to make target `/Users/rbryant/go/src/github.com/nexodus-io/nexodus/internal/api/public/model_models_add_invitation.go', needed by `dist/.go-lint-linux'.  Stop.
make: *** Waiting for unfinished jobs....
```
It looks like go-lint tried to run at the same time as the client code gen, and it caught it at a time when one of the generated files didn't exist. The fix included here has two parts:
* Make a default target for all of these generated files which depends on the target for `client.go`.
* Set the `client.go` target as an order-only dependency of the go-lint targets. The `openapi-client-gen` order-only pre-req was not sufficient, as the dependency checked was the go …
> Makefile: Ensure code gen runs before go-lint

- integration-tests/api_test.go
- integration-tests/proxy_test.go
- internal/api/public/api_devices_custom.go
- internal/api/public/model_models_add_invitation.go
- internal/client/ResourceSyncer.go
- internal/nexodus/nexodus.go
feat: add a Informer() api method that provides a locally cached device list that is synchronized with the apiserver using watch events.
* nexd now reconciles against informer and trigger new reconcile loops when the informer changes.
> feat: nexd now uses the watch api to get device change events.

- .github/workflows/enforce-labels.yml
- docs/development/pull-requests.md
* Note that every person on the Reviewers list should be given a chance to review before merging.
* Document the `hold` label which is an even more explicit way to block merging for whatever reason.
* Fix some minor spelling mistakes.
> docs: Update PR merge criteria

- .dockerignore
- .github/workflows/build.yml
- .github/workflows/deploy.yml
- Containerfile.nexd
- Makefile
- cmd/nexctl/main.go
- cmd/nexd/main.go
- contrib/rpm/nexodus.sysconfig
- integration-tests/helper_test.go
- internal/nexodus/nexodus_linux.go
If nexd is run without a service URL, use a default URL that is set at
build time. If no `NEXODUS_BUILD_PROFILE` is set, it will use the `dev`
profile which will use the local dev service URL. The build profile can
be set to `qa` or `prod` which will set `qa.nexodus.io` or
`try.nexodus.io` as the default URLs.
For the `nexd` container image that gets published to quay.io and the
binary builds published to s3, they are now build with the `prod`
profile in CI.
For those using the rpm, update the default in the sysconfig file
to our public service. This would be the most likely config for an
install using the package.
This change also updates `nexctl` with the same behavior.
> nexd: Set default service URL

- .github/workflows/dev-ec2.yml
- internal/client/apiclient.go
- ops/ansible/aws/ansible.cfg
- ops/ansible/aws/setup-ec2/tasks/main.yml
- Async polling shaves off 20m+ on large scale tests. This lets us wedge in an xlarge. Id like to get to automating 100nodes in the xlarge size.
- Ansible starts falling apart with much more than the default forks, may script some of the plays.
- Adjusted the http.Transport to 10s from 5s as I saw some http header wait timeouts when doing 30 concurrent joins. 5s was likely too aggressive.
> Add async polling for ec2 playbooks and scale tuning

- .github/mergify.yml
- .github/workflows/build.yml
Start experimenting with Mergify by creating an auto-merge rule for dependabot changes that pass CI.
A new "build-workflow-complete" job was added to capture the full completion of the build workflow. This makes configuration a lot simpler.
issue #852
> Auto merge dependabot changes that pass CI

- .github/workflows/qa-scale.yml
- docs/development/scale-testing.md
- hack/e2e-scripts/kctool/kctool.go
- ops/ansible/aws/deploy-ec2-qa.yml
- ops/ansible/aws/qa/qa-deploy-mesh/tasks/main.yml
- ops/ansible/aws/qa/qa-deploy-relay/tasks/main.yml
- Adds a workflow for running qa playbooks against the qa env.
- Most of the playbooks were reusable from dev-ec2. Only 2 new sets were made since self-signed certs isn't a thing in QA.
- Added a tool to add and delete users to a keycloak instance which generates unique UIDs by the same method as in e2e.
- Scale sizing is chosen at dispatch, which sets the Ansible vars from GH secrets.
- Verified there is no credential leakage in any output.
> Add scale testing for use against the QA deployment

- cmd/nexd/main.go
- docs/development/design/nexodus-connectivity.md
- docs/user-guide/discovery-and-relay.md
- integration-tests/integration_test.go
- integration-tests/proxy_test.go
- internal/nexodus/nexodus.go
Given that we have the stun based discovery in the agent itself, relay based discovery function is now
redundant.
> Remove the discovery functionality in the Relay node

- Makefile
By depending on `ui-fmt` instead of `dist/.ui-fmt`, the generate target determined it needed to run every time. This change makes the target only run when necessary.
Running `make all` a second time is back to doing nothing.
> Makefile: get `make generate` to settle

- contrib/rpm/nexodus.spec.in
When installing nexodus on a new host, nexd failed to start because wireguard-tools didn't get pulled in as a dependency. The reason is because the dependencies were in the wrong section of the spec file. With this change, wireguard-tools will be pulled in automatically as desired.
> rpm: Fix dependency installation

- contrib/rpm/nexodus.service
The systemd service unit configuration was missing the Install section, which is required for doing `systemctl enable nexodus` to have it automatically started on boot.
> systemd: Fix autostart on boot

- cmd/nexd/main.go
Arguments placed after the service URL are treated as additional
positional arguments which are all ignored. Detect this and return
with an error making it clear that the arguments were formed
incorrectly.
> nexd: Detect misplaced arguments

- internal/nexodus/join.go
- internal/nexodus/nexodus.go
- internal/nexodus/nexodus_linux.go
- internal/util/retry_operation.go
- internal/util/retry_operation_test.go
- ops/ansible/aws/ansible.cfg
- ops/ansible/aws/deploy-mesh/tasks/main.yml
- ops/ansible/aws/qa/qa-deploy-mesh/tasks/main.yml
- ops/ansible/aws/validate-connectivity/tasks/main.yml
- In scale testing we are seeing http timeouts when a large numbers of agents try and connect concurrently. Part of adding some resilience under load is a retry timer for operations prior to entering the reconcile routines.
- If any of these fail after the retries exiting probably makes more sense than an infinite backoff and let systemd manage restarts from there. TBD.
- Playbooks are modified just for testing of this while it is in draft as the relay node scale bug is still outstanding.
- Renamed `device` to `modelsDevice` since it overlaps with the `golang.zx2c4.com/wireguard/device` package.
- Closes #855  and #867
> Adds a retry to the initial agent setup API calls

- .github/workflows/qa-dev.yml
- .github/workflows/qa-scale.yml
- ops/ansible/aws/validate-connectivity/tasks/main.yml
- On bulk simultaneous joins, IPAM is skipping some addresses for a tbd reason. Using `nexctl connections` probes peers so makes more sense to use and validate in the process.
> Use nexctl to validate connectivity in qa

- .github/workflows/build.yml
If the only thing in a PR is a mergify config change or a config change with associate docs, don't run the build workflow.
> ci: Don't run build workflow on mergify config changes

- .github/mergify.yml
- docs/development/pull-requests.md
Add two more merge rules to be enforced by mergify.
1) Require a label that says user-facing docs are included or to state
that they are not required.
2) Require a label that says design docs are included (or were
previously written and merged), or that they are not required.
> mergify: Require design and user doc verification

- .github/mergify.yml
Automatically add and remove the `needs-rebase` label on PRs based on conflicts with the base branch. When adding the label, mergify will also post a comment notifying the author that a rebase is required.
> mergify: Notify submitters of conflicts

- internal/nexodus/nexodus.go
- internal/nexodus/nexodus_darwin.go
- internal/nexodus/utils_darwin.go
The nexd-wireguard-go is known to allow port reuse so that nexd can discover it's external endpoint address using STUN requests.
> fix: use the nexd-wireguard-go binary if it can be found on the path.

- .github/mergify.yml
If the docs label and/or the design docs label is missing from a PR,
apply a label that gives a hint about what is missing.
> mergify: Give hints via labels about doc label requirements

- .github/workflows/actionlint.yml
- .github/workflows/build.yml
- .github/workflows/deploy.yml
- .github/workflows/qa-dev.yml
- .github/workflows/qa-scale.yml
- Makefile
- Makefile: Add action-lint target
- actions: Remove unused line in actions workflow
- ci: Fix shellcheck wranings
- ci: Add workflow to lint github action workflow config
Closes #909 
commit 3e1fccb124b5f5d2982fdfa0d3b4d41a3290aefa
Date:   Mon Apr 24 22:19:46 2023 -0400
Makefile: Add action-lint target
This target runs the `actionlint` tool to lint our github action
workflows. Find more about `actionlint` here:
https://github.com/rhysd/actionlint
commit f7bc42744a5d38a375a7b53fdf0e5801624e2823
Date:   Mon Apr 24 22:15:09 2023 -0400
actions: Remove unused line in actions workflow
actionlint pointed out that nothing sets `target`, so this …
> Add linting for GitHub actions workflows

- deploy/nexodus-client/overlays/dev/kustomization.yaml.sample
- deploy/nexodus-client/overlays/sample/kustomization.yaml.sample
- deploy/nexodus-monitoring/base/apiproxy-service-monitor.yaml
- deploy/nexodus-monitoring/base/apiserver-service-monitor.yaml
- deploy/nexodus-monitoring/base/grafana-dashboard.yaml
- deploy/nexodus-monitoring/base/grafana-datasource.yaml
- deploy/nexodus-monitoring/base/grafana.yaml
- deploy/nexodus-monitoring/base/jaeger.yaml
- deploy/nexodus-monitoring/base/kustomization.yaml
- deploy/nexodus-monitoring/base/prometheus-service.yaml
- deploy/nexodus-monitoring/overlays/dev/kustomization.yaml
- deploy/nexodus-monitoring/overlays/dev/prometheus-rbac.yaml
- deploy/nexodus-monitoring/overlays/dev/promtheus-ingress.yaml
- deploy/nexodus-monitoring/overlays/rosa/apiproxy-service-monitor.yaml
- deploy/nexodus-monitoring/overlays/rosa/apiserver-service-monitor.yaml
- deploy/nexodus-monitoring/overlays/rosa/kustomization.yaml
- deploy/nexodus-monitoring/overlays/rosa/prometheus-rbac.yaml
- deploy/nexodus/overlays/dev/kustomization.yaml
- deploy/nexodus/overlays/prod/kustomization.yaml
- deploy/nexodus/overlays/qa/kustomization.yaml
- deploy/nexodus/overlays/released/kustomization.yaml
This PR:
1. Splits out the prometheus RBAC config for dev and rosa
1. Removes Ingresses in ROSA (for now) since somehow Grafana is made available through an openshiftapps.com route
1. Fixes a deprecation warning from kustomize
> deploy/monitoring: Stack of (speculative) changes required to get monitoring working in ROSA

- .github/mergify.yml
- .github/workflows/actionlint.yml
When the github actions config is changed, enforce that the `actionlint` check was successful before automatically merging the PR.
> mergify: Enforce actionlint check

- deploy/nexodus/base/apiproxy/deployment.yaml
- deploy/nexodus/base/apiserver/deployment.yaml
- deploy/nexodus/base/frontend/deployment.yaml
Keycloak has to use Recreate, or the realm import won't work.
go-ipam is unknown, but we don't redeploy very often at all so it won't hurt.
> deploy: Use RollingUpdate for Nexodus components

- .github/workflows/deploy.yml
- Makefile
- docs/quickstart.md
- docs/user-guide/agent.md
Fedora 38 is now GA and includes Go 1.20. Update to f38 as our minimum
version so that we can require Go 1.20.
Closes #916
> rpm: Drop f37 support

- docs/user-guide/nexd-proxy.md
I noticed a diagram in the `nexd proxy` docs used an incorrect port
number in one spot.
> docs: fix typo

- go.mod
- hack/stun-client/stun-client.go
This is helpful to doing quick stun queries from the command line for
testing purposes. You can query a single stun server or have it do two
queries and compare the results to see if you're behind symmetric NAT.
Co-authored-by: Russell Bryant <rbryant@redhat.com>
> hack: Add a stun-client utility

- .github/mergify.yml
- docs/development/pull-requests.md
Ensure test coverage is either present or not required by using label
enforcement in the same way as is done for user docs and design docs.
> mergify: Add tests checklist item via label enforcement

- internal/nexodus/nexodus.go
- nexd: Reduce nesting in reconcileDevices()
- nexd: Make temporary dns failures a debug log instead of error
commit b27133ab9bfbef5cb2ade557beb45cfbea363e90
Date:   Thu Apr 27 22:02:38 2023 -0400
nexd: Reduce nesting in reconcileDevices()
Reduce the nesting a few levels in this method to make the flow easier
to follow.
commit d4b9c2773653426367727f803991fe7a6a06c144
Date:   Thu Apr 27 22:12:54 2023 -0400
nexd: Make temporary dns failures a debug log instead of error
When nexd has a temporary failure to resolve DNS for the api server,
just log it to debug instead of error. This is a normal, expected
condition to hit periodically. In my …
> nexd: Reduce error logs

- docs/user-guide/nexd-proxy.md
- integration-tests/proxy_test.go
- integration-tests/util_test.go
- internal/nexodus/nexodus_userspace.go
- internal/nexodus/userspace_proxy.go
- internal/nexodus/wg.go
commit a3b5f4ecae8a94b64ab5d098581b024b470c1b73
Date:   Wed Apr 19 01:28:29 2023 -0400
nexd: Add IPv6 tunnel IP to the userspace proxy device
The userspace proxy device was configured only with the IPv4 tunnel
address. This adds the IPv6 address to the device, as well.
commit e50511b811e220a126955d15940b364fd76c9dbc
Date:   Tue Apr 18 19:21:05 2023 -0400
nexd: Add ingress UDP proxy support
Add ingress UDP proxy support along with a corresponding e2e test.
commit 1a6e05847256715ce8b24a5621ccdddc10b2634d
Date:   Wed Apr 19 01:29:30 2023 -0400
e2e: Add IPv6 TCP …
> nexd: Add ingress UDP proxy support and IPv6 proxy support

- .github/workflows/deploy.yml
Use the common Go env setup for the publish-rpms job. It was still
using Go 1.19, so rpm builds were broken.
> ci: Use go 1.20 in publish-rpms

- Makefile
I ran into two issues with `make gen-openapi-client`. First, the
generated files would be owned by root, causing errors when trying to
reformat the files later. The fix for this is to add `--user` to the
docker command so it users the same user and group IDs as the user
running `make`.
The file permission errors were confusing, because I would see them
later, not during `gen-openapi-client`.
The Makefile tried to reformat the files within the `gen-openapi-client`
target, but it didn't actually work. make was evaluating
`$(shell gofmt -l .)` prior to the code being generated, so the check
to see if this was empty was wrong. Instead, we need the command to run
by the underlying shell when make gets to that line of execution.
For me, what this meant was that every time `gen-openapi-client` …
> Makefile: Fix file permissions for gen-openapi-client

- .github/workflows/deploy.yml
Now that this job is using our custom go setup action, there's more that
can be removed since it's already taken care of.
> ci: Remove more steps from publish-rpms

- cmd/nexctl/connectivity.go
- cmd/nexctl/local_unix.go
- cmd/nexd/main.go
- docs/development/design/userspace-mode.md
- docs/user-guide/nexd-proxy.md
- go.mod
- go.sum
- integration-tests/proxy_test.go
- internal/nexodus/ctlserver.go
- internal/nexodus/nexodus.go
- internal/nexodus/userspace_proxy.go
commit b50e8aeae81d15824ac51c1bd95812b42d77877c
Date:   Thu Apr 20 20:09:01 2023 -0400
nexctl: Add dynamic proxy rule management
Add the following commands to `nexctl` for dynamic proxy rule
management in `nexd`.
- `nexctl nexd proxy list`
- `nexctl nexd proxy add`
- `nexctl nexd proxy remove`
Each `add` or `remove` can contain multiple ingress and egress rules
to add or remove at the same time.
Add an e2e test that exercises all of these commands.
commit 5c7a50c3bf4f7e0e767f2d0276bfbda53a216d3e
Author: Hiram Chirino <hiram@hiramchirino.com>
Date:   Sat Apr 29 13:21:49 2023 -0500
feat: store dynamically added proxy routes between restarts
Signed-off-by: Hiram Chirino …
> nexctl: Add dynamic proxy rule management

- .github/mergify.yml
dependabot PRs do not require the docs/tests/design labels to merge, so exclude those PRs from the rules that apply the labels indicating that required labels are missing.
Do the same change for draft PRs. The label noise isn't necessary on drafts.
> mergify: Remove label requirements for dependabot changes

- Containerfile.dev
- Containerfile.nexd
- Containerfile.test
- MAINTAINERS.md
- contrib/rpm/nexodus.spec.in
- docs/user-guide/scenarios/kubernetes-edge.md
- internal/cucumber/sql.go
- internal/nexodus/nexodus.go
- internal/nexodus/nexodus_darwin.go
- internal/nexodus/nexodus_linux.go
- internal/nexodus/utils_linux.go
- internal/util/Ignore_error.go
The wg cli tool was being used to configure the WG interface.  We now do it with the wgctl go module.
> nexd: drop the requirement to install the wireguard tools.

- internal/nexodus/nexodus.go
I just hit a seg fault on this fmt.Errorf() line because resp was nil.
Update the code to only include the header if resp is not nil.
> nexd: Avoid segfault in error handling

- internal/nexodus/nexodus.go
The Reconcile logic had a flaw where the same peer could be appended to
the `newPeers` list twice. I haven't observed a direct failure as a
result, but I spotted it because of some suspicious debug output while
debugging a different issue.
> nexd: Avoid duplicates in the newPeers list

- integration-tests/helper_test.go
- integration-tests/proxy_test.go
- internal/nexodus/userspace_proxy.go
- nexd: Reject proxy rules with a blank dest host
- e2e: Update nexdStatus() check to include tunnel IPs
- e2e: Run proxy tests in parallel again
commit bd241e2827326427129a6c35330d20b73e0aa59f
Date:   Tue May 2 15:19:05 2023 -0400
nexd: Reject proxy rules with a blank dest host
Proxy rules with a blank destination host should be considered invalid.
Add a check for this and a test case.
I have observed a failure in e2e tests where proxy rules were configured
this way as a result of an earlier error. The original error would have
been easier to spot if the rule had been outright rejected.
commit a86ebc9e9ef6531a204cb99bf3e8e4e6643eea67
Date: …
> Address proxy test reliability

- Makefile
Add a target to print the version string that is embedded in binaries at
build time.
> Makefile: add version target

- integration-tests/proxy_test.go
> e2e: Fix major flaw in TestProxyInvalidConfig

- internal/nexodus/stun_linux.go
Was seeing the following panic:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9ebaf3]
goroutine 1 [running]:
github.com/pion/stun.(*TextAttribute).GetFromAs(...)
/go/pkg/mod/github.com/pion/stun@v0.4.0/textattrs.go:127
github.com/pion/stun.(*Software).GetFrom(...)
/go/pkg/mod/github.com/pion/stun@v0.4.0/textattrs.go:79
github.com/nexodus-io/nexodus/internal/nexodus.stunMsgParse(0x4?, {{0x1, 0x2}, 0x44, {0x13, 0xb8, 0xe7, 0xf5, 0x84, 0xda, ...}, ...})
/src/internal/nexodus/stun_linux.go:119 +0x133
github.com/nexodus-io/nexodus/internal/nexodus.stunRequest(0xc0002df290?, {0xb9c2f5?, 0xb6618a?}, 0xc00009c000?)
/src/internal/nexodus/stun_linux.go:61 +0x365 …
```
> fix: null pointer panic in linux stun requets

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- Makefile
- contrib/rpm/nexodus.spec.in
- docs/quickstart.md
- docs/user-guide/agent.md
commit 3c9c14d5407d1d642aecd76e618e9d0a0cb31d0a
Date:   Tue May 2 13:32:51 2023 -0400
rpm: Add centos-stream-9 support
Add support for building rpms for centos-stream-9-x86_64. Turn on
automatic builds in copr for this distro, as well.
Centos Stream 9 doesn't include Go 1.20 or some of the rpm golang macros
available in Fedora.
commit ce56d1eac1906536ef18e00fd85e56da052a1f26
Date:   Thu May 4 07:40:24 2023 -0400
docs: Note support of CentOS Stream 9
commit b71b7a996e6fffa6092836a72bf80e0382c46391
Date:   Thu May 4 07:46:44 2023 -0400
ci: …
> rpm: Add centos-stream-9 support

- .github/workflows/deploy.yml
Publishing rpms to our rpm repo was broken for Centos Stream 9 because
of accidentally not setting this variable when building the srpm.
> ci: Fix publish-rpm job

- cmd/nexctl/local_unix.go
- cmd/nexctl/main.go
- integration-tests/proxy_test.go
- ops/ansible/aws/validate-connectivity/tasks/main.yml
Rename `nexctl connections` to `nexctl nexd connections`.
Everything else that interacts with `nexd` is under that subcommand.
Other subcommands relate to resources in the Nexodus API.
> nexctl: Move connections command under nexd

- SECURITY.md
GitHub advised creating this file with a security policy that includes what versions are supported and how vulnerabilities are reported. This came from the community guidelines checklist.
> Create Security Policy document

- docs/user-guide/scenarios/kubernetes-edge.md
I noticed this document still mentioned zones. It was only in the
section that instructed the reader to set up a relay. Since a relay is
not required in most casees, I just dropped the section instead of just
adjusting the zone references.
> docs: Drop mention of zones

- contrib/rpm/nexodus.spec.in
I noticed that nexodus was not getting restarted as I regularly updated
the package. The reason was that I had used `%systemd_postun` instead
of `%systemd_postun_with_restart`. I went ahead and removed the extra
stuff checking to make sure these systemd scriptlets exist, because they
seem to exist for both distro versions we are building rpms for right
now. This simplifies the spec file a bit.
I also dropped the build requirement on `make`. It is not used.
> rpm: Restart nexodus on package upgrade

- internal/nexodus/wg_deploy.go
Recent commits moved other peering setup details to be debug messages,
so this one stands out as not helpful on its own with the debug
counterparts.
> nexd: Move peer setup msg to debug

- internal/nexodus/nexodus.go
Previously, nexd produced a log message that said "Device belongs in
organization: ..." prior to creating the device. I found this a little
bit confusing, so I combined the logs into one that says "registered
device into organization".
Here is the specific new log message from my dev environment:
{"level":"info","ts":1683742835.132936,"caller":"nexodus/nexodus.go:426","msg":"Successfully
registered device with UUID: [ f7dc75ae-3d35-4541-b690-812a6a21c3a5 ]
into organization: [ admin (351e9543-fddb-4234-ad53-af9da8ba837c) ]"}
> nexd: Merge two device registration logs

- .github/workflows/deploy.yml
- Makefile
- contrib/rpm/nexodus.spec.in
You'd think `centos-stream-9` is the right mock root to build CentOS
Stream 9 packages, but it is not. When you enable a copr repo on CentOS
Stream 9, it enables the `epel-9` repository for that copr project, not
the `centos-stream-9` repo.
When doing this build with mock, `epel-9` is not sufficient. You must
also specify the base distro that `epel-9` is applied on top of, so
there we must specify `centos-stream+epel-9`.
> rpm: Build centos-stream-9 rpms in the right root

- internal/nexodus/nexodus.go
- internal/nexodus/stun_darwin.go
- internal/nexodus/stun_linux.go
- internal/nexodus/stun_windows.go
- The symmetric disocvery logs are only on the initial statrtup. As we add a reconciler we may want to dial the successful log back but in the meantime this will help with debugging. Lets get stable with STUNs before we roll to symmetric checking in a reconcile.
- Removed a duplicate log printing the NAT binding results and made the debug msg the same across all three OSs.
> Add logging for symmetric nat discovery

- .github/workflows/build.yml
It is still in the Makefile to run locally, but it's failing in CI and
it's not obvious why. It works locally at least. I'll have to look at
this later.
> ci: Drop go-licenses job

- contrib/mac/io.nexodus.nexd.plist
- docs/quickstart.md
- docs/user-guide/agent.md
- mac: Add plist file to run nexd as a daemon
- docs: Reorganize agent install instructions
- docs: Document running nexd with launchd on mac
commit 9f7cc98eaebf7c31943cf35df68f660eca199307
Date:   Fri Apr 28 22:27:35 2023 -0400
mac: Add plist file to run nexd as a daemon
Add the file needed to run `nexd` as a daemon under launchd on mac.
commit 069191308227d8559d83d0f87bd756a594c9634c
Date:   Sat Apr 29 19:41:15 2023 -0400
docs: Reorganize agent install instructions
Reorganize the agent install docs to include install+run instructions
together instead of split across 2 sections.
Signed-off-by: Russell Bryant …
> Support running as a daemon on Mac

- internal/stun/stun.go
- internal/stun/stun_test.go
- resolves getting an empty string as a stun server
> Trim stun server list to prevent an empty string being returned

- Containerfile.nexd
- Makefile
- hack/update-ca.sh
This change includes a couple of updates to `make run-nexd-container`.
First, the commands for running `nexd` against a dev instance, qa, or
prod, are now in the bash history. You can hit the up arrow to choose
which one you want to execute.
Start up with tmux. You can use it the exact same way as before, but it
also makes it easy to add new splits or windows if desired. I frequently
want this because I'm launching nexd, and then I want to run additional
commands either to run a client or server or some kind to test
connectivity.
> hack: Add tmux to nexd container

- deploy/nexodus-monitoring/overlays/rosa/grafana-patch.yaml
- deploy/nexodus-monitoring/overlays/rosa/grafana/kustomization.yaml
- deploy/nexodus-monitoring/overlays/rosa/grafana/ocp-injected-certs.yaml
- deploy/nexodus-monitoring/overlays/rosa/grafana/role.yaml
- deploy/nexodus-monitoring/overlays/rosa/grafana/rolebinding.yaml
- deploy/nexodus-monitoring/overlays/rosa/grafana/route.yaml
- deploy/nexodus-monitoring/overlays/rosa/grafana/secret.yaml
- deploy/nexodus-monitoring/overlays/rosa/grafana/serviceaccount.yaml
- deploy/nexodus-monitoring/overlays/rosa/kustomization.yaml
- deploy/nexodus-monitoring/overlays/rosa/monitoringstack.yaml
- deploy/nexodus/components/promtail/kustomization.yaml
- deploy/nexodus/components/promtail/promtail-daemonset.yaml
- deploy/nexodus/overlays/prod/kustomization.yaml
- deploy/nexodus/overlays/qa/kustomization.yaml
- Run Promtail as a DaemonSet and attempt to add correct incantations to get it started on OpenShift.
- Authenticate access to Grafana using OpenShift
Fixes: #1024
> deploy: OpenShift Auth for Grafana / Promtail as a DaemonSet

- .github/workflows/build.yml
- .github/workflows/deploy.yml
See if this is the issue for our image builds taking a while.
Apparently context: . means that `.git` will get pulled in which is not
deterministic. That can cause the cache not to be hit.
Updates: #1038
> .github: Remove context from docker-build-push action

- integration-tests/helper_test.go
- integration-tests/integration_test.go
- The test suite will teardown containers. When debugging the latest dependabot testcontainer release, e2e was hanging on teardown. This will let us bump to the latest testcontainers-go release once merged  #1018 
- Also removed some residual wg commands that were silently failing that I noticed in the runtime logs.
> Remove redundant testcontainer teardown

- docs/user-guide/scenarios/nexd-proxy-in-kube.md
The nexlink design doc (docs/development/design/nexlink.md) described
3 demos to be produced before implementing nexlink itself. This is
demo1.
This shows how to run `nexd proxy` in a Pod to expose a Kubernetes
Service to a Nexodus Organization.
> docs: Document demo1 from the nexlink design

- cmd/nexd/main.go
- integration-tests/integration_test.go
- internal/handlers/device.go
- internal/handlers/device_test.go
- internal/handlers/user.go
- internal/util/ip_utils.go
- internal/util/ip_utils_test.go
- Adds a function and tests to compare the existing vs new prefix request.
- Adds e2e that tests for this condition.
- Tracked in #982
- IPAM errors out of a default route is added as a child prefix
since that creates an overlap. Its not important to store an
exit-node prefix in IPAM, so this skips adding a 0.0.0.0 or ::/0
as a child-prefix.
- Adds ipv6 child prefix support.
> Check if the ChildPrefix is the same as the existing in UpdateDevice

- deploy/nexodus/base/apiproxy/files/envoy.yaml
- deploy/nexodus/base/apiserver/service.yaml
- deploy/nexodus/base/frontend/service.yaml
and poll DNS every 1s for service membership changes.
Hopefully, this helps avoid Envoy returning 503 responses when we deploy updates.
> convert the apiserver and frontend services to be headless 

- docs/user-guide/scenarios/nexd-proxy-in-kube.md
This covers the 2nd demo scenario originally described in the nexlink
design document. This writeup gives instructions for recreating the
scenario to see it working.
I also added a bit of additional content to the end of the demo 1
section.
> docs: add proxy-in-kube demo 2 content

- Containerfile.nexd
- docs/quickstart.md
- hack/update-ca.sh
For quick testing and demo purposes, provide instructions for
launching a nexd container that can be quickly connected to our demo
service.
> docs: Update quickstart with docker instructions

- .github/workflows/qa-scale-containers.yml
- ops/ansible/aws/ansible.cfg
- ops/ansible/aws/deploy-ec2-qa-containers.yml
- ops/ansible/aws/qa/qa-containers-deploy-mesh/tasks/main.yml
- ops/ansible/aws/qa/qa-deploy-relay/tasks/main.yml
- ops/ansible/aws/qa/validate-connectivity-qa-containers/tasks/main.yml
- This adds a containerized qa workflow option in order to scale up the amount of nodes we can concurrently test while reducing the time to run a test since we are provisioning far less VMs by replacing the agents in containers.
- This also comments out some Ansible optimizations for high node counts that might create issues on low resource nodes that are getting hammered with runtime installs. Leaving them commented as they may go back in once this is in tree and can be further tested.
- This doesn't disrupt any other QA and is standlone.
- Also adds the ability to pick an ec2 instance type, since if you wanted to spin up 100 containers across 5 nodes, you would need to choose a larger machine than the default t2.micro. There are reasonable defaults for smaller tests.
- Creates a new …
> Containerize QA

- integration-tests/proxy_test.go
This test case occasionally fails when `nexd` did fail, but
`containerExec()` did not return an error. Add a backup check for a
fatal log message as another confirmation that a failure occurred.
> e2e: Improve reliability of TestProxyInvalidConfig

- cmd/nexctl/local_unix.go
- cmd/nexctl/peers.go
- docs/quickstart.md
- integration-tests/proxy_test.go
- internal/nexodus/ctlpeers.go
- ops/ansible/aws/validate-connectivity/tasks/main.yml
- The adds `nexctl nexd peers list` to display peer information from the wg interface
- Also consolidates `nexctl nexd connections` under peers to now be `nexctl nexd peers ping` which is a cleaner UX.
- This also adds back debugging functionality we lost from wg binary removal.
> Add the ability to get wg information from the interface via nexctl

- internal/nexodus/nexodus.go
The code that automatically reconciles the public NAT binding was not
getting skipped if we had already determined we are behind symmetric
NAT. This simple change fixes the flapping observed when behind
symmetric NAT.
There is another bug still present, though. This code should be
updated further to detect moving in and out of networks with symmetric
NAT. I will file a follow-bug on that scenario.
Closes #1001
Closes #1044
> nexd: Don't reconcile with stun when behind symmetric NAT

- internal/nexodus/nexodus.go
- internal/nexodus/nexodus_unix.go
- internal/nexodus/wg_deploy.go
- internal/nexodus/wg_iface.go
In general, to have the most robust reconciliation possible, we should
no reconciliation related code that runs differently the first time
vs. subsequent times. This change moves the code in that direction.
nexd was blocking during startup on completion of the first reconcile
call. It dow defers that to the reconciliation go routine. The only
functional difference is that if the first reconciliation fails, we no
longer exit the process. It will keep trying and logging each failed
attempt, which I believe is more desirable behavior.
The Reconcile() method took a `firstTime` parameter, but the
difference in behavior was very minor. The only functoinal differences
were an additional debug log message and a fatal log message if
setting up the wireguard config failed. Instead, nexd will come …
> nexd: Remove some firstTime code for reconciliation

- cmd/nexctl/peers.go
- internal/nexodus/ctlpeers.go
- internal/nexodus/dump.go
- internal/util/utils.go
Add support for running `nexctl nexd peers list` when running in proxy
mode. This requires collecting peer data using a different API, but
all of the same information is available. It also required updating
`nexctl` to handle parsing the handshake timestamp in a 3rd format.
This was manually tested by running `nexd proxy ${SERVICE_URL}`,
letting it peer like usual, and then running the peer list command.
Closes #1066
> nexd: Support listing peers in proxy mode

- cmd/nexd/main.go
- internal/nexodus/nexodus.go
- Adds a retry to symmetricNatDisco() in case one of the two lookups fail.
- Adds a log message if a node is Symmetric but the org does have a relay.
- Issue #1043
> Add a retry to failed STUN lookups on initilization

- internal/nexodus/nexodus.go
- internal/nexodus/wg_deploy.go
- internal/nexodus/wg_peers.go
- nexd: Store peer configs in a map
- nexd: Utilize map in DeployWireguardConfig
- nexd: Reduce some peer config duplication
commit c0c46eb6118df68ad0ff964e383804e762bf2173
Date:   Thu May 25 16:19:28 2023 -0400
nexd: Reduce some peer config duplication
There were a couple places where some code was slightly duplicated
when building peer configs. This cleans it up a bit.
commit f16f158821659fed9f2667265ccb3b84623fd8a6
Date:   Thu May 25 16:00:25 2023 -0400
nexd: Utilize map in DeployWireguardConfig
This method was O(n^2) before. We can now get the wireguard config for
each updated peer as a map lookup instead of a linear search. …
> Store peer configs as a map

- integration-tests/features/device-api.feature
- internal/handlers/device.go
- internal/models/device.go
- Joining as symmetric, and then joining from a non-symmetric was being read as nil by the pointer in the device update handler so the node would always return the device as true, even when it was updating with ax.symmetricNat false.
> Resolve an issue with switching from symmetric to non-symmetric

- contrib/nexctl-docs.sh
- docs/user-guide/nexctl.md
Update the `nexctl` docs with usage information based on the help
text. This doc can be automatically updated using the
`contrib/nexctl-docs.sh` script.
There is plenty of cleanup or additions that could be made. If the
help text is improved or expanded, that will make its way to the doc
site as well by running this script.
Closes #1049
> docs: Add nexctl usage docs

- ui/src/pages/Dashboard.tsx
- useTheme() from "react-admin" returns a ThemeType | RaThemeOptions type, neither of which appear to have a palette property.
- added a strict js check for the theme '==='.
- should allow for #1089 to be merged.
> Use Material-UI theme for useTheme from @mui/material/styles

- internal/nexodus/nexodus.go
- internal/nexodus/wg_peers.go
There was a traversal of the device cache looking for a relay to save
off the relay tunnel IP. Move this code into an existing traversal of
the device cache to be more efficient when the device cache gets large.
> nexd: Eliminiate a traversal of the device cache

- .github/mergify.yml
When scanning open PRs, I often want to know if there are already
changes requested waiting for the PR submitter. This will automate
adding/removing a label that says "changes-requested" when there are
outstanding requests for changes from review.
> mergify: Add a label when changes are requested on a PR

- Makefile
- cmd/nexctl/main.go
- cmd/nexd/main.go
- contrib/bash_autocomplete
- contrib/rpm/nexodus.spec.in
- docs/user-guide/agent.md
- cmd: enable bash autocomplete
- Inclue bash_completion in the manual install packages
- rpm: install bash completion for nexd and nexctl
Closes #1121
commit 668916613dd89df780e85d79ea3230f4850be649
Date:   Sun Jun 4 19:04:25 2023 -0400
cmd: enable bash autocomplete
Bash completion is supported natively by urfave/cli. We just have to
turn it on and use the bash_completion script that comes with the
library.
The script can either be installed automatically by a package or
installed manually.
commit d1ba5185f4e9b57dd4bbc24be50165f2405a7128
Date:   Sun Jun 4 19:40:09 2023 -0400
Inclue bash_completion in the manual install packages …
> Add bash autocompletion for nexctl and nexd

- integration-tests/security_group_test.go
Add some additional validation to the output of `nft list` to validate
that it is empty or not-empty as expected.  While working on some
changes, this made a certain failure much more obvious.
> e2e: Add additional validation to nft list output

- .github/mergify.yml
Remove the rules that add/remove the changes-requested label.
This does not behave as I expected. It adds the label when I wanted,
but it does not remove it. I expected the label to get removed as soon
as someone re-requests review after changes had been requested.
Instead, that state doesn't change until that reviewer approves the
PR. Based on this behavior, it's not a state we can rely on to signal
when a PR is ready to be reviewed again.
> mergify: Drop use of changes-requested label

- .github/workflows/deploy.yml
- Makefile
- rpm: Support building aarch64 rpms on a mac
- rpm: Publish aarch64 rpms
commit f0018e32edea790539afedb5248ece128187f70c
Date:   Tue Jun 6 16:46:51 2023 -0400
rpm: Support building aarch64 rpms on a mac
- Add a shortcut for building the aarch64 mock environments,
`make image-mock-aarch64`.
- Use `-u` instead of `--utc`. `-u` is more portable as it works on
mac, while `--utc` only works on Linux (or `date` from GNU
coreutils).
- Use the mock build root image instead of `latest` when generating
man pages. That way it's not accidentally using an x86_64 image on
an aarch64 host.
With these changes, I can run these commands on my mac to generate
aarch64 rpms:
```
make image-mock-aarch64
MOCK_ROOT=fedora-38-aarch64 make rpm
```
Signed-off-by: …
> Publish aarch64 rpms for Fedora and CentOS Stream

- internal/nexodus/nexodus.go
- internal/nexodus/wg_deploy.go
Adjust the security group reconciliation logic so that it can also be
relied on at startup. This removes some startup-specific code and just
relies on the reconcile loop to do the right thing.
CLoses #1132
> nexd: Adjust security group reconciliation

- internal/nexodus/nexodus.go
- Change this from debug to informational to notify the user security groups are only supported on Linux.
> Change no security group supoport for non-linux to informational

- .github/workflows/deploy.yml
- Makefile
When building an srpm to submit to copr for an aarch64 build, just
build the srpm in an x86_64 build root. The arch doesn't matter when
building the srpm, and it'll be more efficient as it will match the
architecture of the host building the srpm.
When setting up the build root for aarch64 for use with `make rpm`,
install `qemu-user-static-aarch64`, as this is needed to build the
aarch64 rpm on an x86_64 host.
Closes #1142
> rpm: Fix building srpm in aarch64 rpm jobs

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- Makefile
Updated name of variable as the variable declared was not the same as what was being referenced. 
This resulted in the following issue in the build, where we echoed an empty string.
```bash
docker run --name mock --rm --privileged=true -v /home/runner/work/nexodus/nexodus:/nexodus quay.io/nexodus/mock:$(echo  | cut -f2 -d'+') \
47
mock --buildsrpm -D "_commit 4c837fd" --resultdir=/nexodus/dist/rpm/mock --no-clean --no-cleanup-after \
48
--spec /nexodus/contrib/rpm/nexodus.spec --sources /nexodus/dist/rpm/ --root 
49
docker: invalid reference format.
```
> fix SRPM variable name in Makefile

- internal/nexodus/nexodus.go
- When the security group ID changes on for example, a SG ID deletion, it triggers a peer config change and redeploys the peerings.
- This patch creates a method that will ignores the two device fields, Revision and SecurityGroupId by setting them to a temporary constant and then does a reflect to check for a diff.
- The bug is described further in #1146
> Ignore security groups in device reconcile

- internal/handlers/security_group.go
- Since we are implicitly allowing traffic in the initial phase we need to be able to reset the tables back to default with an empty rule being installed.
- The only limitation here is denying all traffic to be addressed in a future PR described in #1162
> Accept empty inbound/outbound SG rules

- .github/workflows/build.yml
The rpms built in the build workflow were in a build artifact called
`nexodus`. It was not obvious at all that this was an archive of rpms
built from this PR. Rename the artifact to "nexodus-rpms". This lets
you install an rpm of a given PR.
I also noticed there was a typo in the job configuration that caused
`el9` to get left out of the rpm filenames for centos stream 9.
> rpm: Rename rpm build artifacts

- internal/api/public/api_organizations.go
- internal/nexodus/userspace_proxy.go
commit b276f998e92ffff3ae4ad36c29c145fb7d051b06
Date:   Fri Jun 9 18:29:56 2023 -0400
nexd: fix a seg fault
I observed a seg fault in a CI run against PR #1007 on the following
line:
```go
proxy.logger.Debugf("Connection from %s closed: %v", conn.RemoteAddr().String(), err)
```
Based on conventions of the std library, as well as reading the code
in wireguard-go, it appears that `conn` should never be `nil` here, as
we only get here after `Accept()` returns `nil` for an error.
However, it is possible that `conn.RemoteAddr()` returns `nil`. Here's
the corresponding code in the `net` library:
```go
func (c *conn) RemoteAddr() Addr {
if !c.ok() {
return nil
}
return c.fd.raddr
}
```
and to further explain when it may be `nil`, here's `c.ok()`: …
> nexd: fix a seg fault

- internal/nexodus/nexodus.go
Security groups are not supported in the userspace proxy mode. I saw
some errors when running `nexd proxy` in a Kubernetes Pod. It was
attempting to run some `nft` commands.
Closes #1180
> nexd: Don't attempt security groups in proxy mode

- cmd/nexctl/connectivity.go
- cmd/nexctl/local_unix.go
- internal/nexodus/ctlconnectivty.go
- internal/nexodus/keepalive.go
- ops/ansible/aws/validate-connectivity/tasks/main.yml
- Adds the command option `nexctl nexd peers ping6`
- Also cleans up some unused constants and a couple of ineffective conditions in keepalive OS.
> Add v6 support for nexd peers ping

- cmd/nexctl/local_unix.go
- cmd/nexctl/peers.go
Update the output of `nexctl nexd peers list` with a minimal list of
columns by default. To get full output, you can use the new `--full`
option. This provides output that won't line wrap in most cases.
Closes #1112
> nexctl: Trim down peers list output

- cmd/nexctl/main.go
- cmd/nexd/main.go
- docs/user-guide/agent.md
- integration-tests/integration_test.go
- internal/nexodus/nexodus.go
Addressing: https://github.com/nexodus-io/nexodus/issues/1179
Changing `org-id` flag to `organization-id`
> updating cli org-id flag to organization-id

- Containerfile.nexd
- Makefile
- cmd/nexd/main.go
- cmd/nexd/pprof_disabled.go
- cmd/nexd/pprof_enabled.go
- docs/development/debugging.md
Go has tooling that makes profiling pretty easy. Add some build
automation and instructions for using it with nexd.
> nexd: Optionally build with pprof support

- cmd/nexctl/main.go
- cmd/nexctl/organization.go
- This was the legacy discovery node option that needs removal
- The database migration to remove it from the org models removal will be a separate PR.
> Remove legacy organization-hub from nexctl

- .github/workflows/build.yml
- Makefile
- cmd/nexctl/main.go
- cmd/nexd/main.go
- docs/deployment/nexodus-service.md
- docs/user-guide/discovery-and-relay.md
- docs/user-guide/nexctl.md
- docs/user-guide/security-groups.md
- hack/nexctl-docs.sh
- internal/nexodus/nexodus.go
- internal/nexodus/nexodus_darwin.go
- internal/nexodus/nexodus_windows.go
- ui/index.html
- ui/src/App.tsx
- ui/src/index.tsx
- ui/src/layout/AppBar.tsx
- ui/src/providers/AuthProvider.tsx
- also set better usage description for the command.
- udpates docs usage.
- `—host` is still supported but deprecated.
- rename controllerUrl field to apiURL.
fixes: #1231
> nexctl: use `--service-url` instead of `--host`.

- .github/mergify.yml
- .github/workflows/build.yml
- .github/workflows/docs.yml
- Prevent build actions from being triggered from a png extended file
> Add *.png to the path-ignore for the build action

- .excalidraw-ignore
- .github/mergify.yml
- .github/workflows/build.yml
- .github/workflows/docs.yml
- Makefile
Ensure images exported from excalidraw include the metadata that
allows them to be re-imported and edited again.
Run png-lint in CI and enforce it with mergify
> ci: Add png-lint to validate excalidraw exports

- .github/workflows/build.yml
There is no `ui` target. This works because the `ui` directory exists,
but it's not doing anything useful.
> ci: Don't run make ui

- Makefile
- cmd/apiserver/main.go
- deploy/nexodus/base/apiproxy/files/envoy.yaml
- deploy/nexodus/base/apiserver/deployment.yaml
- deploy/nexodus/base/apiserver/service.yaml
- docs/development/design/rate-limiting.md
- go.mod
- go.sum
- hack/ext-authz-client/main.go
- internal/handlers/api.go
- internal/handlers/envoy_authz.go
- internal/handlers/handlers_test.go
- internal/routers/middleware.go
- internal/routers/routers.go
- pkg/oidcagent/handlers.go
We were stuffing the AccessToken in a browser cookie. With this change we get the AccessToken from the redis session.  This lowers the amount of data placed into browser cookies to just being the Redis session id.
This will also give us a place to implement per device API token in the future.
> apiserver: implement ext_autz grpc endpoint

- cmd/nexctl/main.go
- integration-tests/helper_test.go
- integration-tests/integration_test.go
When no device is registered as peers, result is empty
related to https://github.com/nexodus-io/nexodus/issues/1165
When only single device is registered
```
nexctl nexd peers list
panic: reflect: call of reflect.Value.FieldByName on map Value
goroutine 1 [running]:
reflect.flag.mustBe(...)
/usr/local/go/src/reflect/value.go:223
reflect.Value.FieldByName({0x50d8a0?, 0x400000e868?, 0x0?}, {0x5b9d86?, 0x1?})
/usr/local/go/src/reflect/value.go:1345 +0x13c
main.showOutput(0x4000368260?, {0x4000311180, 0x3, 0x4cc980?}, {0x50d8a0?, 0x4000169dd0})
/src/cmd/nexctl/main.go:612 +0x7a4
main.cmdListPeers(0x18?, {0x5b54b1?, 0x6?})
/src/cmd/nexctl/peers.go:73 +0x118
main.init.1.func8(0x4000358000?)
/src/cmd/nexctl/local_unix.go:212 +0x3c
[[github.com/urfave/cli/v2.(*Command](http://github.com/urfave/cli …
```
> fixing panic on peer list due to empty map

- ui/package-lock.json
- ui/package.json
Dependeabot reports that minimist <0.2.4 has a critical vulnerability,
CVE-2021-44906. The bot has been unable to resole this automatically.
This change forces a fixed version to be used, even if a dependency
that uses it has not been updated.
https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides
https://github.com/nexodus-io/nexodus/security/dependabot/23
> ui: Override minimist to >=0.2.4

- ui/package-lock.json
- ui/package.json
- ui/vite.config.ts
The dependencies of vite-plugin-favicon have blocked resolution of
multiple ui CVEs. This alternative does the same thing, but works with
newer dependencies.
This should resolve:
- https://github.com/nexodus-io/nexodus/security/dependabot/15
- https://github.com/nexodus-io/nexodus/security/dependabot/37
- https://github.com/nexodus-io/nexodus/security/dependabot/47
> ui: switch to vite-plugin-favicons-inject

- Makefile
- deploy/nexodus/base/redis/redis-statefulset.yaml
They were leaving the service in a bad state where clients would get API errors.  We now made redis non-peristent and bounce it after clearing the DB.
> fix: `make clear-db` and `make recreate-db`

- docs/development/scale-testing.md
- hack/e2e-scripts/qa-kind-container-scale.sh
- This handles the self-signed cert as well as the custom hostname.
- Putting this in a seperate script to keep both as simple as possible.
> Add a script for running standalone QA tests against a KIND stack

- Makefile
Resolves the error:
`go: -race requires cgo; enable cgo by setting CGO_ENABLED=1`
> Enable cgo in e2e make

- cmd/nexctl/peers.go
- integration-tests/integration_test.go
- Spent some time trying to get it working with the showOutput function but getting it to handle a map started getting messy. Can revisit but just want to resolve the panic and get it working again for now.
Output looks like the following:
```
$> sudo ./nexctl-dev-linux-arm64 nexd peers list
PUBLIC KEY                                       ENDPOINT                  ALLOWED IPS                    LATEST HANDSHAKE     TRANSMITTED     RECEIVED     HEALTHY
XXXXXXXXXXXX1BGN57LMTdHMVgosVnaQ7oPhXNXkfDI=     XXX.236.195.180:18303     [100.64.0.3/32 200::3/128]     85 seconds ago       7844            7792         true
```
> Resolve the nexctl peer list panic

- Makefile
- cmd/nexd/main.go
- integration-tests/helper_test.go
- integration-tests/kube_test.go
- internal/state/kstore/kstore.go
- internal/state/kstore/kstore_off.go
That PR tripled the size of the nexd binary, so we decided to not  compile it in by default to rethink how to accomplish the same goal a  different way.
To build with the kstore code run: `NEXODUS_BUILD_TAGS="kubernetes" make clean dist/nexd`
> Don’t compile in the kstore code introduced in dd822f7

- Containerfile.dev
- Containerfile.nexd
- Adds about 30m for the wg user space binary. Will be useful to debug user issues and QA early on. We currently get information such as peer listings and stats directly from the wg interface but if nexd isn't running those stats aren't available. Since nexd does not rely on this it is removable at any time but would like to have it available for time saving for installs for now.
> Add wireguard userspace tools to the nexd image

- internal/nexodus/nexodus.go
- internal/nexodus/nexodus_windows.go
- internal/nexodus/route_windows.go
- internal/nexodus/utils_windows.go
- internal/stun/client.go
- Supressed debug logs from failed STUN lookups since windows is currently unable to resuse the wg port for STUNs.
- Filled out some no-ops in unimplemented routing functions v4/v6.
- More details in #1343
> Cleaning up windows logging and routing

- Containerfile.nexd
- cmd/nexd/main.go
- internal/nexodus/nexodus.go
Closes issue #1383
- nexd: Add tcpdump to nexd container image
- nexd: Restore timestamps in logs
- nexd: Fix peering health monitoring
commit 805b6bfe6699198a80a4fb2c364e58e66d9c8da3
Date:   Fri Sep 8 11:14:10 2023 -0400
nexd: Add tcpdump to nexd container image
We include a set of useful debugging tools in the image. I needed
tcpdump today to debug something. It seems useful to include. It's
just over 1 MB.
commit 0eb2f522fde750c6dd34543dabb5ab2f3ee788d0
Date:   Fri Sep 8 11:15:55 2023 -0400
nexd: Restore timestamps in logs
My original reason for dropping the timestamps was two-fold: systemd
timestamps the logs for nexd and the timestamp …
> nexd: Fix peering health monitoring

- .github/workflows/deploy.yml
This isn't working, and it looks like nobody uses it anyway. Just drop
it for now.
> rpm: drop aarch64 rpm build for epel9

- internal/nexodus/nexodus.go
- internal/nexodus/utils_darwin.go
- internal/nexodus/utils_linux.go
- internal/nexodus/utils_windows.go
- Currently, the only indication we give that the user is running without elevated privleges is throwing a fatal that nexd doesn't have permissions to create a directory. This adds an early check for administrator/root for OS mode.
> Add elevated privileges check at nexd runtime

- .github/workflows/deploy.yml
- Containerfile.frontend
Trying to get frontend-image to work in the arm64 build that is failing in deploy. Also sets a 90m timeout since the build is running the full default 360m (6hrs) until bailing.
> Bump node and buildx

- ui/package-lock.json
- ui/package.json
- ui/vite.config.ts
- rollback until we can get vite-plugin-favicons-inject building on arm64 in GH CI or any alternative solution to address the vuln. It builds on an arm64 locally but will not in the deploy workflow for some reason. Vite debugs don't show anything, it simply hangs on the rendering chunks rollup. This will get deploy working again and unblock prod if this works for the team.
> Rollback vite-plugin-favicon-inject

- .gitignore
- hack/e2e-scripts/scale/check-connectivity.sh
- hack/e2e-scripts/scale/check-errors.sh
- hack/e2e-scripts/scale/check-nexd-status.sh
nexd agent onboarded across the organizations.
Useful when you have >1K containers running and want to detect how many devices/nexd didn't onboard successfully.
> Add utility script to check nexd status of all the

- deploy/nexodus/base/apiserver/deployment.yaml
- deploy/nexodus/base/auth/deployment.yaml
- deploy/nexodus/base/database/postgres.yaml
- deploy/nexodus/base/ipam/deployment.yaml
- deploy/nexodus/overlays/dev/kustomization.yaml
- deploy/nexodus/overlays/playground/files/envoy.yaml
- deploy/nexodus/overlays/playground/files/limits.yaml
- deploy/nexodus/overlays/playground/kustomization.yaml
Commit contain following changes that is required to scale control plan to support 10K devices.
- Use pgbouncer for postgres database connection pooling to ensure clients doesn't run out of connections for requests.
- Update apiserver, ipam and auth deployment to use pgbouncer rather than directly using postgres db.
- Update base auth deployment to explicitly set resource limits, so that overlays can override it.
- Add patroni configuration to base database deployment, to configure max_connections and shared_buffer for database server for scale scenario. Base deployment is set to default values, individual overlays can overwrite it.
- Configure PGBouncer to specify pool size and reserve pool per database, rather than per database server.
- Add envoy files in playground overlay, to update …
> Playground manifest configuration updates to support 10K devices

- .github/workflows/promote.yml
- This synchronizes the agent binary with the prod promotion ref.
- Docs updates will be in a followup PR once binaries are verified in the proper places from the next deploy.
> Add nexd binaries with prod promotion

- deploy/nexodus/base/apiproxy/deployment.yaml
- deploy/nexodus/base/apiproxy/files/envoy.yaml
- deploy/nexodus/base/apiproxy/ingress.yaml
- docs/development/design/watch-api.md
- integration-tests/api_test.go
- integration-tests/features/events-api.feature
- internal/api/public/api_devices_custom.go
- internal/api/public/api_organizations.go
- internal/api/public/api_organizations_custom.go
- internal/api/public/api_security_group_custom.go
- internal/api/public/model_models_watch.go
- internal/docs/docs.go
- internal/docs/swagger.json
- internal/docs/swagger.yaml
- internal/handlers/events.go
- internal/handlers/stream.go
- internal/models/watch_event.go
- internal/nexodus/nexodus.go
- internal/util/json.go
Depends on #1382, this provides a shared informer so that a single REST api call can be used to watch multiple types of events like device or security group changes.
> Implements a shared informer API for nexd

- Makefile
- deploy/nexodus/components/limitador/kustomization.yaml
- deploy/nexodus/components/promtail/kustomization.yaml
- deploy/nexodus/overlays/dev/files/promtail.yaml
- deploy/nexodus/overlays/dev/kustomization.yaml
- deploy/nexodus/overlays/playground/kustomization.yaml
- deploy/nexodus/overlays/qa/kustomization.yaml
Kustomize release 5.1.0 (our CI job uses this version) made the changes in the order of processing of resources, components , generators and transformers. That requires that our top level kustomization yamls should create the configmaps, rather than replace it, because with 5.1.0, components will be processed after generators, so there won't be any existing configmap to replace.
Following issue has more details about it:
https://github.com/kubernetes-sigs/kustomize/pull/5170
> Update playground/qa manifest to adopt changes from latest kustomize release

- internal/handlers/events.go
Flush the response headers in the event stream before waiting for the next event.
> fix: avoid ‘net/http: timeout awaiting response headers’ in nexd

- hack/localip/main.go
This utility depended on nexodus, but for some reason this breaks the
build for me at the moment on mac. It's harmless enough to just copy
in the code we use here. This lets me move on and still run `make
run-nexd-container` on mac for the moment.
> localip: drop nexodus dependency

- contrib/debian/nexodus.conf
- contrib/debian/nexodus.service
- contrib/rpm/nexodus.service
- contrib/rpm/nexodus.sysconfig
The way args were passed to `nexd` made it so all arguments were
passed as a single argument to the process. This change makes it work
as expected.
> systemd: Fix support for multiple nexd arguments

- internal/handlers/device.go
- internal/handlers/device_metadata.go
- internal/handlers/events.go
- internal/handlers/handlers.go
- internal/handlers/invitations.go
- internal/handlers/organization.go
- internal/handlers/security_group.go
- internal/handlers/user.go
this also lets up bump the gorm version and still pass the unit tests.
We wanted all the db middleware passed to the scopes method to always get applied, but it seems there are edge cases where the they are not always applied.
> fix: don’t use the gorm Scopes() method, it’s behavior is more complex than we realized.

- deploy/nexodus/overlays/prod/kustomization.yaml
I'm getting a 500 error trying to connect a device and there's no
hints in the logs about why. Turn on debug to see if anything else
pops up to help.
> deploy: Enable apiserver debug in prod

- deploy/nexodus/overlays/arm64/kustomization.yaml
`make run-on-kind` was failing on apple silicon macs.
> fix: the arm64 overlay to work with recent pgbouncer changes.

- .github/workflows/qa-dev.yml
The failure showed that the wildcard was not interpreted. Use another
method that will hopefully expand the wildcard.
The failure:
> cat: './ops/ansible/aws/*-connectivity-results.txt': No such file or directory
> qa-dev: Fix globbing in workflow

- ops/ansible/aws/validate-connectivity/tasks/main.yml
A previous change tried to do this, but missed a spot that the
filenames needed to change to be unique per host.
> qa-dev: Collect mesh connectivity from all nodes

- cmd/nexctl/device.go
- Converted to local time as well just as a personal preference.
- If the device is no longer online, clear the field.
- The OnlineAt value is only changed to a user-friendly time for column output mode.
> Add the online health status to device list in nexctl

- internal/api/public/api_auth.go
- internal/docs/docs.go
- internal/docs/swagger.json
- internal/docs/swagger.yaml
- internal/routers/routers.go
- pkg/oidcagent/handlers.go
- pkg/oidcagent/router.go
- ui/src/providers/AuthProvider.tsx
- This should resolve the hard logout after the initial token expires after 300s. The logic is the OIDC token Refresh() kicks off 5sec before the exp in the keycloak token is set to expire and gets updated with a new refresh token. More details on this method at: https://marmelab.com/blog/2020/07/02/manage-your-jwt-react-admin-authentication-in-memory.html
- Tokens are still managed on the server-side so the client side is not dealing with storage. There are pros and cons for both methods.
- Safari private-mode is the only scenario that doesn't work here, but Safari is notorious for its strictness in cookies so it is likely something related.
- This handles multiple logins from separate browsers on the same host etc.
> Add token refresh to client side web ui

- Makefile
- cmd/nexd-kstore/main_off.go
Also make the build a little less noisy by suppressing a go warning.
> build: add the --context arg kubectl commands to avoid targeting the wrong cluster.

- ui/package-lock.json
- ui/package.json
- ui/src/pages/SecurityGroups/SecurityGroupEditRules.tsx
- The predefined ports were getting passed as-is instead of being normalized to a proper protocol, e.g., MYSQL needs to be mapped to TCP to be punched into netfilter. The secgroup rules validation patch brought this to the surface. The ports do not grey out as they did, but I added a todo to do it in another patch to avoid regression here.
- Remove ALL TRAFFIC as an option and replace with tooltips
- Since we are implicitly allowing all traffic it makes more sense to give the user a message to remove all rules to allow all traffic.
- Adds a tooltip explaining adding a rule will implicitly begin dropping all other traffic that isn't explicitly allowed.
- Screencaps for all of the changes in comments.
> Aliased predefined ports in sec group rules edit UI

- hack/install-tools.sh
If the go bin dir does not exist, this script installs kubectl as
$GOPATH/bin, instead of putting kubectl in the bin directory. This
patch ensures the directory is created if it does not exist.
> install-tools: Don't assume go bin dir exists

- deploy/nexodus/overlays/prod/files/promtail.yaml
- deploy/nexodus/overlays/prod/kustomization.yaml
Kustomize release 5.1.0 (our CI job uses this version) made the changes
in the order of processing of resources, components , generators and
transformers. That requires that our top level kustomization yamls
should create the configmaps, rather than replace it,
because with 5.1.0, components will be processed after generators,
so there won't be any existing configmap to replace.
Following issue has more details about it: https://github.com/kubernetes-sigs/kustomize/pull/5170
> Update prod manifest to adopt changes from latest kustomize release

- ui/src/pages/Devices.tsx
- ui/src/pages/SecurityGroups/SecurityGroupEditRules.tsx
- ui/src/pages/SecurityGroups/SecurityGroupStructs.tsx
- ui/src/pages/SecurityGroups/SecurityGroupTable.tsx
- ui/src/pages/SecurityGroups/SecurityGroups.tsx
A few highlight:
- Pre-canned protocols such as MySQL/SSH are aliased along with regular rules such as tcp are defined as aliases in the SecGroup structure file to make the code more manageable.
- Combined the pre-defined IP range and the User defined IP range and also populate based on the user typing if there is a match in the predefined rules list. Otherwise it is a new element in the field.
- Added a tooltip to explain the user needs to hit enter after added a rule. That is a limitation of freeSolo with React AutoComplete as far as I can tell but its good for meow. Additional tooltip icons added as well.
- Tasks tracked in #1477
> SecGroup UI bugs fixes and improvements

- ui/src/pages/SecurityGroups/SecurityGroupEditRules.tsx
- ui/src/pages/SecurityGroups/SecurityGroups.tsx
- React won't render unless the state has changed. This fixes an issue where only the first save in a rules edit it sent via a notification. This resets the state so react will see a diff and fire the notification for all rule saves.
> Reset the notifcation state to have it re-render on change

- internal/nexodus/keys.go
These come up during startup, but seem more like debug info.
> nexd: Move some keys log msgs to debug

- ui/src/pages/Devices.tsx
Not a huge fan of the click to new window view as is without breadcrumbs. This adds an accordion view but still preserves the click view for now. The accordion view contents are the DeviceShow FC.
> Add an accordian view to UI device listing

- integration-tests/security_group_test.go
- internal/handlers/security_group.go
- internal/handlers/security_group_test.go
- internal/nexodus/policy_linux.go
- ui/src/pages/SecurityGroups/SecurityGroupEditRules.tsx
- broke out a v4/v6 case statement that should have been two different cases.
- Added support for a missing agent implementation of a ipv4 or ipv6 rule with an ip range and ports specified using the transport header "th" option as follows:
```json
{
"from_port": 123,
"ip_protocol": "ipv4",
"ip_ranges": [
"100.64.0.0/10"
],
"to_port": 456
},
{
"ip_protocol": "ipv6",
"from_port": 123,
"to_port": 456,
"ip_ranges": [
"0200::/8"
]
}
```
- tracked in #1470
> Security group agent side rule fixes

- Makefile
- contrib/rpm/nexodus.spec.in
The nexodus service config was not properly marked as a config file in
the rpm spec file. This resulted in overwriting the config every time
the package was upgraded. With this change, if the package includes an
updated version of the default configuration is put in a
`nexodus.rpmnew` file.
In passing, the git hash used in the version is now explicitly limited
to 6 characters. It's usually 6, but when I got a longer one, it broke
my rpm build.
Closes #1495
> rpm: don't overrwrite config on upgrade

- internal/nexodus/nexodus.go
- internal/util/retry_operation.go
This patch improves the behavior of nexd at startup when it has an
invalid auth token stored. The most common time to see this is when
switching a host to use a different service endpoint, such as
switching between dev, qa, and prod.
This makes nexd clear the invalid auth token and restart the auth
process. The backoff behavior has been adjusted from constant to an
exponential backoff. This ensures the first retry happens quickly,
since in this common scenario the first will fail, but the second
attempt will succeed, so we want to get to that second try quickly. If
the failure is something else, then we want to start backing off.
> nexd: Handle invalid tokens at startup

- cmd/nexctl/connectivity.go
- internal/nexodus/ctlconnectivty.go
- internal/nexodus/keepalive.go
- internal/nexodus/nexodus.go
- internal/nexodus/wg.go
- internal/nexodus/wg_peers.go
- ops/ansible/aws/validate-connectivity/tasks/main.yml
The most common scenario addressed by this change is that after
failing to peer via a peer's local IP or reflexive IP, we can fall
back to using a relay if one is available.
More generally, these changes give a chosen peering method a chance to
work and then fall back to alternative methods. For more examples:
- An attempt to peer via local IP will fall back to peering via 
reflexive IP
- An attempt to peer via reflexive IP will fall back to using a relay.
- If there is not currently a healthy relay available, it will fall
back to the beginning and choose the first available method to try 
These retries will keep going until something works, or it will stay
with the relay if one is available. When using a relay, other methods
will be retried after the API sends us changes to a device that …
> nexd: dynamic peering

- cmd/nexctl/connectivity.go
```
HOSTNAME     WIREGUARD ADDRESS     LATENCY     PEERING METHOD     CONNECTION STATUS
ub-arm       100.64.0.5            6.83ms      direct-local       ✓ Reachable
```
> Move nexctl connection status to the last column for aligment

- .github/workflows/build.yml
Im seeing e2e fail with complaints about disk space on the runner. Removing some unnecessary files resolves it in the short term. ¯\\_(ツ)_/¯ I'm curious what would have tipped us over the limit here as well, but getting e2e functional again and back tracking from there seems rational, unless of course someone resolves the root cause first! Only thing that merged for the most part since its failing has been dependabots.
References:
`https://github.com/actions/runner-images/issues/2875`
`https://github.com/actions/runner-images/issues/2840`
Example runner log and the job [6461383807](https://github.com/nexodus-io/nexodus/actions/runs/6461383807):
```
e2e-integration (dev)
Unhandled exception. System.IO.IOException: No space left on device : …
```
> Free up space to avoid runners running out of disk in e2e

- .github/workflows/build.yml
Adds inline caching which should help with disk space and time for layers that haven't changed between builds.
Free space at the end of the workflow is now `/dev/sdb1   14G  4.1G  9.0G  31% /mnt`.
```
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        84G   77G  6.7G  92% /
tmpfs           3.4G  172K  3.4G   1% /dev/shm
tmpfs           1.4G  5.7M  1.4G   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/sda15      105M  6.1M   99M   6% /boot/efi
/dev/sdb1        14G  4.1G  9.0G  31% /mnt
tmpfs           693M   12K  693M   1% /run/user/1001
```
> Runner space optimizations and cleanup

- integration-tests/proxy_test.go
This e2e test is one that we commonly see some failures from. For
example, the  last one I saw showed 4 responses received via UDP
instead of 5. Since it's UDP, and we're running these tests in
parallel so load could be an issue at times, allow for some drops as
long as we receive the majority of responses we expected.
> e2e: Allow for some packet drops in udp tests

- Makefile
- internal/nexodus/wg_peers.go
- internal/nexodus/wg_peers_test.go
- nexd: Refactoring to allow easier unit testing
- Makefile: honor GOTESTSUM_FMT for unit tests
- nexd: Add peering choice unit tests
commit 86e1484330ff68778645d3162c5015fe390b10a2
Date:   Fri Oct 20 13:19:07 2023 -0400
nexd: Refactoring to allow easier unit testing
Refactor code that makes peering method decisions to make it easier to
build unit tests. Tests will be introduced in following commits.
commit e089aff0eac5af34291208ac5805e299a9db876a
Date:   Fri Oct 20 16:30:27 2023 -0400
Makefile: honor GOTESTSUM_FMT for unit tests
commit 55149588c206c839fcba0c0c258f82e4a231227d
Author: …
> nexd: peering unit tests, round 1

- internal/nexodus/nexodus.go
- internal/nexodus/wg_peers.go
- internal/nexodus/wg_peers_test.go
- nexd: Fix delay of peering fallback
- nexd: adjust rebuildPeerConfig() return values
- nexd: Expand peering unit tests
- nexd: Fix peering reset when no relays are present
- nexd: Add 3rd level peering fallback unit tests
commit 8de00491a5b700bc5da9074cafa365b9817a11d0
Date:   Mon Oct 23 16:50:16 2023 -0400
nexd: Add 3rd level peering fallback unit tests
This change introduces tests for a 3rd level of peering fallback. It
covers cases like:
direct -> reflexive -> relay
or if no relay was present:
direct -> reflexive -> direct
It also ensures that peering doesn't change once we fall back to a
healthy relay.
commit e2cebf9f618173b14268e7b847bcc84f9d4b18a7
Author: Russell Bryant …
> nexd: Add unit tests for peering method fallback and fix some bugs

- internal/nexodus/ctlexit.go
- internal/nexodus/exit_origin.go
- internal/nexodus/route_darwin.go
- internal/nexodus/route_linux.go
- internal/nexodus/route_windows.go
- Fixes an issue where exit nodes were being duplicated in `exitNodeOrigins` if the endpoint address changed. It now keys off the public key to avoid duplication.
```
nexctl nexd exit-node list
ENDPOINT ADDRESS        PUBLIC KEY
192.168.64.2:56997      Wneb+xx6481iaWB2eohZmEttZzar+G7R6A0hoBYkJBQ=
192.168.64.2:55374      Wneb+xx6481iaWB2eohZmEttZzar+G7R6A0hoBYkJBQ=
```
- Adjust nexctl to display the local node if it is an exit node. Currently, if the local node is an exit node it is omitted from the nexctl output of `nexctl nexd exit-node list`. It only adjusts the nexctl output since it is operating as intended since it is using peer data from the api-server.
> Exit node fixes

- docs/user-guide/security-groups.md
- internal/nexodus/exit_client.go
- internal/nexodus/exit_node.go
- internal/nexodus/exit_origin.go
- internal/nexodus/net_router.go
- internal/nexodus/nexodus.go
- internal/nexodus/policy_darwin.go
- internal/nexodus/policy_darwin_test.go
- internal/nexodus/policy_linux.go
- internal/nexodus/policy_windows.go
- Adds v4/v6 policy support via PF for darwin.
- Creates a PF anchorfile in `/etc/pf.anchors/io.nexodus` and copies the main pf.conf for loading to avoid modifying a system file.
> Add PacketFilter policy support for macOS

- .github/workflows/promote.yml
Closes #1554
GH doesn't return a job ID from a dispatch so this timestamps and queries qa-dev for runs after the timestamp. This should work in all scenarios since qa-dev is in a concurrency group and shouldn't conflict with other dispatches. More on the API limitation [here](https://github.com/orgs/community/discussions/9752).
I validated the API calls in a fork and they are functional. Going to draft this until Monday when we promote next.
> Add qa-dev to promote for promotion validation

- Makefile
Makefile run-on-kind target deploy the dev manifest and that pull the redis image. Sometime this end up failing because of `Too many request` error from docker hub, and you endup wasting some time. This change pulls and load the image before the manifest deployment, so if it fails, it fail fast.
Fixed typo in namespace `delete` command.
> Pull and load redis image to Kind cluster

- integration-tests/routing_test.go
TestExitNode hit an endpoint at cloudflare to test internet
connectivity. They're having an outage at the moment, so switch to a
well known google IP (their DNS service) instead.
> e2e: Drop cloudflare endpoint from test

- ui/src/pages/SecurityGroups/SecurityGroupEditRules.tsx
- ui/src/pages/SecurityGroups/SecurityGroups.tsx
The paths for the security-groups API changed in our recent round of
API updates. This change adjusts the security-groups page ti use the
new APIs.
> ui: fix security groups after API changes

- internal/nexodus/keepalive.go
Before: 
`icmp_seq=1, time=%!d(float64=55.618917)ms`
After: 
`icmp_seq=1, time=46.12ms`
> Fix the float debug printing

- internal/handlers/invitations_test.go
go-lint is throwing gosec G601 error on main branch.
```
nexodus git:(main) go version
go version go1.21.3 linux/amd64
➜  nexodus git:(main) make clean
➜  nexodus git:(main) make go-lint
[GO LINT]    GOOS=linux
internal/handlers/invitations_test.go:89:21: G601: Implicit memory aliasing in for loop. (gosec)
UserID:         &c.userID,
^
make: *** [Makefile:185: dist/.go-lint-linux] Error 1
```
> Fix for gosec G601 error

- cmd/nexctl/security_group.go
- integration-tests/features/security-group-api.feature
- integration-tests/helper_test.go
- internal/handlers/security_group.go
- internal/handlers/security_group_test.go
- internal/models/security_group.go
- internal/util/string.go
This allows a user to update individual fields of a security group. We now sort by the group name instead of by id.
Add more api feature tests around security-groups.
> nextctl: make all fields of the sg update optional.

- internal/api/public/model_models_device_start_response.go
- internal/client/apiclient.go
- internal/docs/docs.go
- internal/docs/swagger.json
- internal/docs/swagger.yaml
- pkg/oidcagent/handlers.go
- pkg/oidcagent/models/models.go
We now compare the local time with server time to compute if the client needs to adjust for client time skew.
> nexd: fixes #1426 If your machine's time is set to 15 mins into the future, nexd will fail to login

- Makefile
- docs/user-guide/nexctl.md
- docs/user-guide/nexd.md
- hack/nexctl-docs.sh
- hack/nexd-docs.sh
- Makefile: auto update nexd/nexctl CLI docs
- docs: Update nexctl docs to include device update
commit 2454d033acd5fe138da0ffb576c3efa8e2376586
Date:   Mon Nov 6 16:01:08 2023 -0500
docs: Update nexctl docs to include device update
commit d607a95c64cb5674c0c4f26528e7af8271e5827c
Date:   Mon Nov 6 15:58:09 2023 -0500
Makefile: auto update nexd/nexctl CLI docs
Make the build process automatically update the generated CLI docs for
nexd and nexctl. CI will also fail if CLI options are changed but the
docs are not updated. The `make generate` job will see uncommitted
changes and fail.
> Ensure CLI docs stay up to date

- cmd/nexctl/device.go
- cmd/nexctl/device_metadata.go
- cmd/nexctl/invitation.go
- cmd/nexctl/main.go
- cmd/nexctl/organization.go
- cmd/nexctl/reg_key.go
- cmd/nexctl/security_group.go
- cmd/nexctl/user.go
- cmd/nexctl/vpc.go
- integration-tests/features/reg-key-api.feature
- internal/cucumber/http_response.go
- internal/handlers/device.go
- internal/handlers/device_metadata.go
- internal/handlers/envoy_authz.go
- internal/handlers/events.go
- internal/handlers/handlers.go
- internal/handlers/invitations.go
- internal/handlers/organization.go
- internal/handlers/reg_key.go
- internal/handlers/security_group.go
- internal/handlers/vpc.go
- internal/models/error.go
* Switch from using Bind*() calls to ShouldBind*() so that we can set the json content type.
* `nexctl` displays improved error messages when API errors occur.
> fixes: #1605 Error responses have the wrong content type set

- cmd/nexctl/local_unix.go
- cmd/nexd/flags_unix.go
- docs/user-guide/nexctl.md
- docs/user-guide/nexd.md
When displaying the default unix socket path, use the privileged mode
default, as that is the common case.
> docs: Use paths for root user in help text

- integration-tests/integration_test.go
- internal/nexodus/nexodus.go
- internal/nexodus/wg_peers.go
- internal/nexodus/wg_peers_test.go
Prior to this change, the only way to reach a child-prefix CIDR was by
peering directly with the device exposing that prefix.
This change updates relay peer configuration to include child-prefix
CIDRs for peers that are reachable via the relay instead of directly.
Closes #1536
> nexd: Add child prefix routing through relays

- ui/src/App.tsx
- ui/src/layout/Menus.tsx
Since users don’t have access to view list other users, it does not make sense to show the Users resource page in the UI, it’s only going to list the currently logged in user.  Maybe we bring it back if we have a Super Admin type role that can view users across different tennants.
> ui: Don’t show the Users menu item.

- internal/nexodus/dump.go
- internal/nexodus/nexodus.go
- internal/nexodus/wg.go
- internal/state/state.go
This issue reported that when a device is restarted, it triggered
upates to be sent to all peers. The reason updates were being sent is
that the Endpoints changed on every restart. When nexd started, it
would allocate a new random UDP listen port. This is bad, because it
means the data plane is interrupted at every restart until peering is
re-established using the new endpoint details.
This change uses the state store to save off the random UDP port so it
can be used on a restart.
There is one other behavior change included here. Previously, for a
relay, the default wireguard port was always used for a relay. Now if
a port is specified via a command line argument, it will be used for
regular devices and relays.
Closes #958
> nexd: reuse the wireguard listen port on restart

- internal/nexodus/ctlstatus.go
- Adjusts the nexd.sock path to be the common symlink for linux and macOS
> Check for existing nexd process on macOS

- integration-tests/integration_test.go
- internal/nexodus/nexodus.go
- internal/nexodus/wg_deploy.go
If either the v4 or v6 tunnel IPs conflict with a CIDR found on an
existing host interface.
I also moved setupInterface() to wg_deploy.go because that was the
only place it was used and it seems like an appropriate enough place
for it.
Closes #24
> nexd: Don't assign tunnel IP if it conflicts with host

- integration-tests/features/device-api.feature
- internal/api/public/api_vpc_devices_custom.go
- internal/handlers/device.go
- internal/nexodus/wg.go
We now null out unique fields of the device record when we delete it.
> fixes #1514 - When a device is deleted it is marked deleted but still  has a unique key in the device table.

- integration-tests/routing_test.go
- Replacing the exit node e2e curl to cflare and replacing it with pings to 8.8.8.8 since we're occasionally seeing resets from the cflare target. This will help determine if the error is due to code or e2e with the external curl target (likely the later with the error code being returned).
> Replace the curl e2e in exit node for tshooting

- .github/workflows/deploy.yml
- Makefile
- docs/quickstart.md
- docs/user-guide/agent.md
- rpm: Enable new repo
- Makefile: Fix action-lint dependencies
Part of #1139
commit 1bc13bdf8e3434bef3e0ed573371fddbaecb7509
Date:   Wed Nov 15 17:00:21 2023 -0500
Makefile: Fix action-lint dependencies
I noticed that the action-lint target didn't run after I made a change
to a github workflow. This fixes it.
commit 7a0172ff3926cb79c2b833508eb28df1cbc36405
Date:   Wed Nov 15 16:53:48 2023 -0500
rpm: Enable new repo
The original rpm repo was russellb/nexodus. This turns on the config
to publish rpms to nexodus/nexodus. For now it will publish to both to
allow some transition. Eventually I'll delete the one under my name.
Signed-off-by: …
> rpm: Rename russellb/nexodus to nexodus/nexodus

- .github/workflows/promote.yml
rollback to it easily if we need to.
> ci: store the previous prod tag as prod-previous so that we can 

- .dockerignore
- .github/workflows/build.yml
- Containerfile.playwright
- Makefile
- hack/update-ca.sh
- integration-tests/features/webui.feature
- integration-tests/features_test.go
- integration-tests/steps_test.go
- internal/cucumber/cucumber.go
- ui/.gitignore
- ui/package-lock.json
- ui/package.json
- ui/playwright.config.ts
- ui/tests-examples/demo-todo-app.spec.ts
- ui/tests-examples/example.spec.ts
- ui/tests/env.ts
- ui/tests/login.spec.ts
Lets see if we can figure out a nice workflow to use these for e2e  and qa testing.
> feat: add an initial spike of playwright UI tests

- cmd/nexctl/device.go
- cmd/nexctl/device_metadata.go
- cmd/nexctl/exit_node.go
- cmd/nexctl/invitation.go
- cmd/nexctl/main.go
- cmd/nexctl/organization.go
- cmd/nexctl/peers.go
- cmd/nexctl/reg_key.go
- cmd/nexctl/security_group.go
- cmd/nexctl/user.go
- cmd/nexctl/vpc.go
Also:
* don’t show output using log, since the timestamps are not needed for interactive commands.
* we more consistently validate all uuids before doing api calls.
> nexctl: clean up api access commands to be simpler and more consistent.

- .github/workflows/qa-saas.yml
- Makes keycloak auth address variable
- Adds a cronjob daily at noon est. This time/occurrence can be adjusted once the workflow is validated as working on another PR.
- Adds a qa/prod controller address option
> Add validation for qa/prod

- ui/src/pages/Devices.tsx
When a device is online, make the checkmark green. A black checkmark
wasn't super clear if that meant it was good or not.
> ui: Color the online status icon

- cmd/apiserver/main.go
enabled argo-cd sync for nexodus-qa and apiserver was failing with following error 
```2023/12/15 05:39:53 could not parse "no-reply@nexodus.io" as bool value from environment variable "NEXAPI_SMTP_FROM" for flag smtp-from: parse error```
> fix for smtp-from flag

- cmd/nexctl/connectivity.go
The output of the `nexctl nexd peers ping` command outputs a friendly
spinner while it runs the ping check with all of the peers. This
change turns the spinner off if the output format in use is one of the
parseable formats.
> nexctl: Don't use spinner for parseable output

- docs/development/design/stack.md
The text was not interpreted as a comment when written this way.
Dropping the `1.` makes it render as intended.
> docs: Fix a rendering error

- Makefile
```
ubuntu@ip-172-31-78-221:~/nexodus$ NEX_TEST=TestFeatures/webui make e2e
.certs directory does not exist, running make cacerts...
make[1]: Entering directory '/home/ubuntu/nexodus'
The local CA is already installed in the system trust store! 👍
```
> Run make cacerts in derpcerts Makefule section if .certs is not present

- .github/dependabot.yml
This groups dependency updates into:
- development deps: github actions updates
- production deps: gomod and/or docker image changes
- nodejs production deps
- nodejs development deps
This should result in no more than 4 PRs each Monday 😏 With less chance of introducing merge conflicts.
> Reduce dependabot PR churn

- .devcontainer/devcontainer.json
- .dockerignore
- Makefile
- docs/development/tooling.md
This feature is not actively used and has caused some confusion with
new contributors trying to run the full test stack in the dev
container, which we don't expect to work.
> Remove vscode devcontainer

- go.mod
- go.sum
1.5.5 does not appear to exist, so I'm getting build errors on a new
system. See https://github.com/txn2/txeh/releases
> go.mod: Depend on txeh 1.5.4

- ui/src/App.tsx
https://marmelab.com/blog/2021/02/02/react-admin-february-2021-update.html#domain-telemetry
I think someone installing their own Nexodus service would be
surprised to find it was sending telemetry to a 3rd party. We could
document it and describe how to disable it, but it's just easier to
disable it by default.
> ui: Disable react-admin telemetry

- cmd/nexctl/invitation.go
- integration-tests/features/invitation-api.feature
- integration-tests/features/organization-api.feature
- integration-tests/features/user-organization-api.feature
- internal/api/public/model_models_add_invitation.go
- internal/api/public/model_models_invitation.go
- internal/api/public/model_models_organization.go
- internal/api/public/model_models_user_organization.go
- internal/database/database.go
- internal/database/datatype/string_array.go
- internal/database/migration_20240221_0000/migration.go
- internal/database/migrations/migrations.go
- internal/docs/docs.go
- internal/docs/swagger.json
- internal/docs/swagger.yaml
- internal/handlers/invitations.go
- internal/handlers/organization.go
- internal/handlers/security_group.go
- internal/handlers/user.go
- internal/handlers/vpc.go
- internal/models/base.go
- internal/models/invitation.go
- internal/models/organization.go
- internal/models/user_organization.go
- internal/util/string.go
- ui/src/components/StringListField.tsx
- ui/src/pages/Invitations.tsx
- ui/src/pages/Organizations.tsx
* added a roles []string field to user_organizations table, can be set to owner|member, allows for additional roles in the future.
* remove the organization owner_id field, as we can find owners using the roles field.
> apiserver: support multiple Organization owners

- deploy/nexodus/base/database/postgres.yaml
We previously requested 2 GB for postgres, but thaut's breaking some
development environments that are memory constrained. Request a
minimum of 1 GB instead.
> deploy: Request 1 GB for postgres

- internal/dnsserver/dnsserver_test.go
- Noticed some failures on this test, bumping the timeout from the default 2s to 5s see if it resolves the flakes.
> Increase the timeout in DNS unit tests

- deploy/nexodus-monitoring/overlays/rosa/monitoringstack.yaml
* argo kept saying the the MonitoringStack resource was OutOfSync due To the namespaceSelector getting clear out by something else.
> deployment: attempt to fix the nexodus monitoring stack on qa/prod

- deploy/nexodus-monitoring/overlays/rosa/grafana-patch.yaml
- deploy/nexodus-monitoring/overlays/rosa/grafana/route.yaml
This reverts commit 4f96ab6c15391c061b1a6f0148028591c7daf13e.
> Revert "deployment: fix grafana host name "

- Makefile
- go.mod
- go.sum
- integration-tests/helper_test.go
- integration-tests/relayderp_test.go
- internal/nexodus/derp.go
- internal/nexodus/in_mem_resolver.go
- internal/nexodus/nexodus.go
- internal/nexodus/nexodus_darwin.go
- internal/nexodus/utils.go
- internal/nexodus/wg_derp_proxy.go
- internal/nexodus/wg_peers.go
- internal/nexodus/wg_peers_test.go
* e2e: avoid using os.env to configure test options as that can cause a data race in concurrent tests.
* add make e2e-setup target that gets you setup to run e2e tests.
* don’t allow direct local connections when the `--peer-only` cli option is used.
* fx data races in derp proxy restart
> Fixes e2e failures on mac
